import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID,verify} from 'node:crypto';
import {harness} from './harness.mjs';
import {submit} from '../src/client.mjs';
import {canonical,digest,verifyBundle} from '../src/crypto.mjs';

test('Korean governance across independent ingress, vault and audit processes preserves measured scope and frozen evidence',async t=>{
 const h=await harness();t.after(()=>h.close());
 const before=new Date(Date.now()-60000).toISOString(),noticeAt=new Date(Date.now()-120000).toISOString();
 const system={id:'kr-http',name:'합성 대출 AI 서비스 공급사',owner:'검토팀',purpose:'대출 심사 보조',markets:['KR'],krRoles:['deployer'],aiBusinessOperator:true,domesticImpact:true,generative:true,highImpact:'confirmed',modelId:'credit-model',modelVersion:'v1',policyVersion:'p1',providedAt:before};
 const saved=(await h.api('/api/governance/systems',{role:'reviewer',body:system})).body;
 const inventory=(await h.api('/api/governance')).body,req=inventory.requirements.find(r=>r.id==='KR-31-1');
 assert.equal(inventory.requirements.filter(r=>r.jurisdiction==='KR').length,18);
 const bytes=Buffer.from('합성 고지 화면과 전달 시험 근거'),documentInput={id:'notice-proof',systemId:system.id,name:'고지 시험.txt',mediaType:'text/plain',contentBase64:bytes.toString('base64'),sha256:createHash('sha256').update(bytes).digest('hex')};
 assert.equal((await h.api('/api/governance/documents',{body:documentInput})).status,403);
 const documentResponse=await h.api('/api/governance/documents',{role:'reviewer',body:documentInput});assert.equal(documentResponse.status,200);const doc=documentResponse.body;
 assert.equal((await h.api('/api/governance/documents/notice-proof/export',{role:'reviewer',tenant:'beta'})).status,404);
 const check={id:randomUUID(),kind:'governance_check',occurredAt:new Date().toISOString(),traceId:'notice-check',actionId:'notice-check',systemId:saved.id,modelId:saved.modelId,modelVersion:saved.modelVersion,policyVersion:saved.policyVersion,clockUncertaintyMs:0,governanceCheck:{schemaVersion:1,requirementId:req.id,checkType:'notice_pre_delivery',result:'pass',systemHash:digest(saved),requirementHash:digest(req),documentHash:doc.sha256,measurements:{noticeAt,providedAt:before,noticeAtUncertaintyMs:0,providedAtUncertaintyMs:0,noticeDelivered:true,deliveryMethod:'screen',methodBasisRecorded:false,targetUsersCovered:true}}};
 assert.equal((await submit(h.ingress.url,h.principal('agent'),check)).status,403);
 assert.equal((await submit(h.ingress.url,h.principal('telemetry'),check,{signature:'0'.repeat(64)})).status,401);
 assert.equal((await submit(h.ingress.url,h.principal('telemetry'),check)).status,202);
 assert.equal((await submit(h.ingress.url,h.principal('telemetry'),check)).body.duplicate,true);
 const assessment={systemId:saved.id,requirementId:req.id,applicability:'applicable',assessment:'sufficient',legalReview:'reviewed',control:'고지 전달 검토',owner:'검토팀',reason:'합성 전달 측정과 복구 가능한 문서를 검토함',nextReviewAt:'2099-01-01T00:00:00.000Z',evidence:[{type:'attestation',ref:'unfetched'}]};
 const missing=await h.api('/api/governance/assessments',{role:'reviewer',body:assessment});assert.equal(missing.status,200);
 assert.equal((await h.api('/api/governance/tasks/'+missing.body.id,{role:'reviewer',body:{status:'closed',reason:'근거 없음'}})).status,409);
 const eventRef={type:'event',ref:'alpha-telemetry/'+check.id};
 assessment.evidence=[{type:'document',ref:'governance-document:'+doc.id},eventRef];
 assert.equal((await h.api('/api/governance/assessments',{role:'reviewer',body:assessment})).status,200);
 const report=async()=>(await h.api('/api/governance/report?systemId='+saved.id)).body;
 const find=r=>r.items.find(i=>i.requirement.id===req.id);
 const first=find(await report()),second=find(await report());
 assert.equal(first.status,'human_evidence_assessed');assert.deepEqual(first.technicalEvidence,second.technicalEvidence);
 assert.equal(first.technicalEvidence.automaticLegalVerdict,false);
 assert.equal((await h.api('/api/governance/tasks/'+missing.body.id,{role:'reviewer',body:{status:'closed',reason:'현재 범위 측정과 사람 검토 확인'}})).status,200);
 await h.analyze();
 const frozenResponse=await h.api('/api/governance/finance/report',{role:'reviewer',body:{systemId:saved.id}});assert.equal(frozenResponse.status,200);const frozen=frozenResponse.body;
 assert.equal(find(frozen.snapshot.governance).status,'human_evidence_assessed');
 assert.equal(frozen.sha256,digest(frozen.snapshot));assert.ok(verify(null,Buffer.from(canonical(frozen.snapshot)),h.publicKey,Buffer.from(frozen.signature,'base64')));
 assert.equal((await h.api('/api/governance/finance/reports/'+frozen.id,{tenant:'beta'})).status,404);
 assert.equal(verifyBundle((await h.api('/api/export')).body,h.publicKey).valid,true);
 await h.api('/api/governance/systems',{role:'reviewer',body:{...system,modelVersion:'v2'}});
 assert.equal(find(await report()).status,'review_required');
 assert.equal((await h.api('/api/governance/tasks/'+missing.body.id,{role:'reviewer',body:{status:'closed',reason:'오래된 모델 측정 재사용'}})).status,409);
 assert.deepEqual((await h.api('/api/governance/finance/reports/'+frozen.id)).body,frozen);
 await h.restart();
 assert.equal(find(await report()).status,'review_required');
 assert.deepEqual((await h.api('/api/governance/finance/reports/'+frozen.id)).body,frozen);
 const exported=await h.api('/api/governance/documents/notice-proof/export',{role:'reviewer'});assert.equal(exported.status,200);assert.deepEqual(Buffer.from(exported.body.contentBase64,'base64'),bytes);
 assert.equal((await h.api('/api/integrity')).body.valid,true);
});
