import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,statSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {verifyPublicQaFresh,verifyPublicQaFreshFixture,FRESH_GENERATION_RESOURCES,freshPromptSha256} from '../scripts/verify-public-qa-fresh.mjs';
import {FRESH_SOURCE_RUN,FRESH_SOURCE_PINS,FRESH_DATA_PINS,FRESH_SCOPE,freshEvaluationJob} from '../scripts/public-qa-fresh-workload.mjs';
import {FRESH_EVALUATION_STAGE} from '../scripts/prepare-public-qa-fresh-evaluation.mjs';
import {QA_IMAGE,QA_BASE_REVISION,QA_NAMESPACE,QA_NODE} from '../scripts/public-qa-workload.mjs';
const sha=value=>createHash('sha256').update(value).digest('hex');
function fixture(t){
 const root=mkdtempSync(join(tmpdir(),'evidscope-fresh-verification-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const put=(name,value)=>{const path=join(root,name);mkdirSync(dirname(path),{recursive:true});const raw=Buffer.isBuffer(value)?value:Buffer.from(typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');writeFileSync(path,raw);return raw;};
 const edit=(name,fn)=>{const value=JSON.parse(readFileSync(join(root,name)));fn(value);put(name,value);};
 const inventory=()=>{const list=[];const walk=(directory,prefix='')=>{for(const name of readdirSync(directory)){const path=join(directory,name),relative=prefix+name;if(statSync(path).isDirectory())walk(path,relative+'/');else if(relative!=='evaluation-receipt.json'){const raw=readFileSync(path);list.push({path:relative,bytes:raw.length,sha256:sha(raw)});}}};walk(join(root,'output'));return list.sort((a,b)=>a.path.localeCompare(b.path));};
 const dataset=Array.from({length:128},(_,index)=>{const context='합성 원문 '+index;return {id:'synthetic_'+index,context,question:'어떤 원문인가?',contextSha256:sha(context),isImpossible:index%2===1};}),dataBytes=put('data/data.jsonl',dataset.map(JSON.stringify).join('\n')+'\n');
 const manifest={schemaVersion:1,stage:FRESH_EVALUATION_STAGE,datasetSha256:sha(dataBytes),rowIds:dataset.map(row=>row.id),qualityClaimAllowed:false,promotionAllowed:false},manifestBytes=put('data/manifest.json',manifest);
 const runId='public-qa-fresh-test-1',candidateIdentity={baseRepository:'fdtn-ai/Foundation-Sec-8B-Reasoning',baseRevision:QA_BASE_REVISION,baseArtifactLockSha256:FRESH_SOURCE_PINS.artifactLockSha256,image:QA_IMAGE,stage:'public_qa_grounding_continuation_v1',maxSteps:20},fixedBinding={schemaVersion:1,mode:'public_qa_fresh_paired_evaluation',stage:FRESH_EVALUATION_STAGE,diagnosticOnly:true,runId,sourceRunId:FRESH_SOURCE_RUN,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:80,sourceTrainingExecutionVerified:true,candidateIdentity,...FRESH_SOURCE_PINS,...FRESH_DATA_PINS,rows:128,baselineExecutedThisRun:true,executionOrder:['baseline','candidate'],baselineKind:'fixed_reasoning_base_without_adapter',evaluationScope:FRESH_SCOPE,qualityClaimAllowed:false,promotionAllowed:false,localHumanReviewPerformed:false};
 const names=['evaluate-public-qa-fresh.py','evaluate-public-qa-diagnostic.py','training_artifacts.py','public_qa_cuda_runtime.py','public_qa_memory_gate.py','public_qa_thermal.py'],runtimeData=Object.fromEntries(names.map(name=>[name,'# Synthetic fixture '+name+'\n'])),runtimeHash=sha(JSON.stringify(runtimeData));
 const fixedInputs={...fixedBinding,binding:fixedBinding,bindingSha256:sha(JSON.stringify(fixedBinding,null,2)+'\n'),runtimeConfigMap:'public-qa-fresh-'+runtimeHash.slice(0,16),runtimeSha256:runtimeHash,runtimeFiles:Object.fromEntries(names.map(name=>[name,sha(runtimeData[name])]))};
 const job=freshEvaluationJob(runId,fixedInputs),binding={...fixedBinding,datasetSha256:sha(dataBytes),manifestSha256:sha(manifestBytes)},bindingBytes=put('data/binding.json',binding),inputs={...fixedInputs,...binding,binding,bindingSha256:sha(bindingBytes),data:'data/data.jsonl',manifest:'data/manifest.json',bindingPath:'data/binding.json'};
 for(const [key,value]of Object.entries({'evidscope.io/dataset-sha256':inputs.datasetSha256,'evidscope.io/manifest-sha256':inputs.manifestSha256,'evidscope.io/binding-sha256':inputs.bindingSha256}))job.metadata.annotations[key]=value;
 const env=job.spec.template.spec.containers[0].env;for(const item of env){const field={EVIDSCOPE_DIAGNOSTIC_DATA_SHA256:'datasetSha256',EVIDSCOPE_DIAGNOSTIC_MANIFEST_SHA256:'manifestSha256',EVIDSCOPE_FRESH_EVALUATION_BINDING_SHA256:'bindingSha256'}[item.name];if(field)item.value=inputs[field];}
 const jobUid='synthetic-job',podUid='synthetic-pod',podName=runId+'-pod',liveSpec={...structuredClone(job.spec.template.spec),nodeName:QA_NODE};
 const controller={schemaVersion:1,runId,jobUid,podUid,podName,mode:'explicit_public_qa_fresh_evaluation',state:'process_completed',startedAt:'2026-10-06T00:00:00.000Z',finishedAt:'2026-10-06T00:10:00.000Z',exit:{exitCode:0,signal:0,reason:'Completed',containerID:'containerd://'+ 'c'.repeat(64),startedAt:'2026-10-06T00:00:01Z',finishedAt:'2026-10-06T00:09:59Z'},terminationConfirmed:true,admission:{allowed:true},trainingRunCompleted:false,qualityClaimAllowed:false,promotionAllowed:false,automaticGovernanceGateClaimed:false,diagnosticOnly:true,inputs,manifest:job,manifestSha256:sha(JSON.stringify(job)),livePodSpec:liveSpec,memoryHigh:{podUid,memoryHigh:'2147483648',memoryMax:'12884901888',containerLeafOnly:true,markerReleased:true}};
 const sample={source:'public_qa_manual_host_probe',observedAt:'2026-10-06T00:00:00Z',host:{source:'trusted_windows_host_probe',freeMemoryGiB:10,cpuPercent:10,gpu:{memoryTotalMiB:12288,memoryUsedMiB:8000,utilizationPercent:10,temperatureC:60}},windows:{physicalFreeGiB:10,commitFreeGiB:16,commitUsedPercent:74,pagesInputPerSecond:1,counterSource:'Win32_OperatingSystem_and_Win32_PerfFormattedData_PerfOS_Memory'},guest:{memAvailableGiB:12,memoryFullAvg10:0},cgroup:{memoryCurrentGiB:2,memoryLimitGiB:12,oomCount:0,oomKillCount:0,cpuMax:'200000 100000'}};controller.startSamples=Array.from({length:3},()=>structuredClone(sample));controller.observations=[{sample:structuredClone(sample),decision:{allowed:true,reasons:[],memoryDomainsSummed:false,gpuInventoryInterpretedAsActiveCompute:false}}];
 put('controller/controller-receipt.json',controller);put('controller/live-job.json',{metadata:{name:runId,namespace:QA_NAMESPACE,uid:jobUid},spec:{template:job.spec.template}});put('controller/live-pod.json',{metadata:{name:podName,namespace:QA_NAMESPACE,uid:podUid,ownerReferences:[{kind:'Job',name:runId,uid:jobUid}]},spec:liveSpec,status:{containerStatuses:[{name:'training',imageID:QA_IMAGE,containerID:controller.exit.containerID,restartCount:0,lastState:{},state:{terminated:controller.exit}}]}});put('controller/runtime-configmap.json',{apiVersion:'v1',kind:'ConfigMap',immutable:true,metadata:{namespace:QA_NAMESPACE,name:inputs.runtimeConfigMap,annotations:{'evidscope.io/code-sha256':runtimeHash}},data:runtimeData});
 const preadmission={schemaVersion:1,datasetSha256:inputs.datasetSha256,manifestSha256:inputs.manifestSha256,beforeAnyModelCall:true,modelCalls:0,admitted:128,excluded:0,answerBasedCropping:false,rows:dataset.map(row=>({id:row.id,inputTokens:100,outputTokenBudget:128,contextTokens:1024,contextSha256:row.contextSha256,fullContextPreserved:true,admitted:true,exclusionReason:null,promptSha256:freshPromptSha256(row),inputIdsSha256:sha('synthetic token IDs '+row.id)}))},admissionBytes=put('output/preadmission.json',preadmission);
 const responses={schemaVersion:1,mode:binding.mode,datasetSha256:inputs.datasetSha256,maxOutputTokens:128,requestTimeoutSeconds:120,baselineExecutedThisRun:true,evaluationScope:FRESH_SCOPE,baseline:{},candidate:{}},logRows=[];
 for(const [sideIndex,side]of ['baseline','candidate'].entries())for(const [index,row]of dataset.entries()){const admission=preadmission.rows[index],value={content:'{"answer":"","evidenceQuote":"","abstained":true}',seconds:1,inputTokens:100,outputTokens:12,timedOut:false,tokenLimitReached:false,inputIdsSha256:admission.inputIdsSha256,promptSha256:admission.promptSha256,callOrdinal:sideIndex*128+index+1,adapterEnabled:side==='candidate'};responses[side][row.id]=value;put(`output/rows/${side}-${row.id}.json`,{id:row.id,side,...value});logRows.push({side,id:row.id,modelCalls:value.callOrdinal,inputIdsSha256:value.inputIdsSha256,promptSha256:value.promptSha256,adapterEnabled:value.adapterEnabled,seconds:1,outputTokens:12,timedOut:false,tokenLimitReached:false});}
 const responsesBytes=put('output/responses.json',responses),cg={'memory.current':'1073741824','memory.peak':'2147483648','memory.max':'12884901888','memory.high':'2147483648','cpu.max':'200000 100000','memory.events':{oom:'0',oom_kill:'0'},'memory.stat':{anon:'1'}};
 const lifecycle={sameLoadedBaseObject:true,adapterLoadedOnce:true,isTrainable:false,modelTraining:false,trainableParameterCount:0,baseArtifactLockSha256:FRESH_SOURCE_PINS.artifactLockSha256,adapterSha256:FRESH_SOURCE_PINS.adapterSha256},adapterStates=Object.fromEntries(['baseline','candidate'].map(side=>[side,{side,adapterEnabled:side==='candidate',observedAdapterModuleCount:128,allAdapterModulesDisabled:side==='baseline',allAdapterModulesEnabled:side==='candidate'}]));
 const receipt={schemaVersion:1,mode:binding.mode,stage:FRESH_EVALUATION_STAGE,runId,diagnosticOnly:true,state:'generation_completed',bindingSha256:inputs.bindingSha256,datasetSha256:inputs.datasetSha256,manifestSha256:inputs.manifestSha256,baseArtifactLockSha256:FRESH_SOURCE_PINS.artifactLockSha256,candidateIdentity,...FRESH_SOURCE_PINS,sourceRunId:FRESH_SOURCE_RUN,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:80,sourceTrainingExecutionVerified:true,controllerExecutionVerified:false,qualityClaimAllowed:false,promotionAllowed:false,localHumanReviewPerformed:false,evaluationScope:FRESH_SCOPE,baselineKind:binding.baselineKind,baselineExecutedThisRun:true,executionOrder:['baseline','candidate'],podUid,deviceId:'synthetic-GPU',image:QA_IMAGE,modelCalls:256,preparedRows:128,admittedRows:128,excludedRows:0,resources:FRESH_GENERATION_RESOURCES,observedQuantComputeDtypes:['torch.bfloat16'],modelLifecycle:lifecycle,adapterStates,cgroupBeforeLoad:cg,cgroupAfterLoad:cg,cgroupAfterGeneration:cg,cudaPeakAllocatedBytes:2**30,cudaPeakReservedBytes:2**30,sideMeasurements:Object.fromEntries(['baseline','candidate'].map(side=>[side,{modelCalls:128,wallSeconds:129,generationSeconds:128,cudaPeakAllocatedBytes:2**30,cudaPeakReservedBytes:2**30,cgroup:cg}])),responsesSha256:sha(responsesBytes),preadmissionSha256:sha(admissionBytes)};
 const persist=()=>{const {responsesSha256,preadmissionSha256,cgroupAfterGeneration,files,...progress}=receipt;put('output/progress.json',progress);receipt.files=inventory();put('output/evaluation-receipt.json',receipt);};persist();
 const writeLog=(records=logRows)=>put('controller/training.log',[{freshModelLifecycle:lifecycle},{freshAdapterState:adapterStates.baseline},...records.slice(0,128),{freshAdapterState:adapterStates.candidate},...records.slice(128)].map(JSON.stringify).join('\n')+'\n');writeLog();
 const options={runDirectory:join(root,'output'),controllerReceipt:join(root,'controller/controller-receipt.json'),workspaceRoot:root};return {root,put,edit,receipt,controller,inputs,dataset,responses,preadmission,logRows,persist,writeLog,options,verify:()=>verifyPublicQaFreshFixture(options)};
}
test('synthetic fresh paired fixture verifies evidence structure while refusing actual source or execution claims',async t=>{const f=fixture(t),r=await f.verify();assert.equal(r.verificationPassed,true);assert.equal(r.syntheticFixture,true);assert.equal(r.verified,false);assert.equal(r.evaluationExecutionVerified,false);assert.equal(r.sourceTrainingExecutionVerified,false);assert.equal(r.modelCalls,256);assert.equal(r.admittedRows,128);assert.equal(r.qualityClaimAllowed,false);assert.equal(r.promotionAllowed,false);await assert.rejects(verifyPublicQaFresh({...f.options,syntheticFixture:true}),/fresh_evaluation_|fixed_pin|ENOENT/);});
test('fresh prompt binding excludes annotation labels, answers and metadata',()=>{const row={question:'질문?',context:'전체 원문',answers:['secret answer'],isImpossible:false};assert.equal(freshPromptSha256(row),freshPromptSha256({...row,answers:['changed'],originalQa:{answer:'hidden'},isImpossible:true}));assert.notEqual(freshPromptSha256(row),freshPromptSha256({...row,context:'다른 원문'}));});
test('bounded same-container terminal recheck accepts the captured running snapshot and rejects unbound recovery',async t=>{const f=fixture(t);f.edit('controller/live-pod.json',v=>v.status.containerStatuses[0].state={running:{startedAt:f.controller.exit.startedAt}});f.edit('controller/controller-receipt.json',v=>v.terminalRecheck={podUid:v.podUid,podName:v.podName,containerName:'training',statusReads:2,observedAt:'2026-10-06T00:09:59.500Z',sampleError:'failed to create exec: task not found'});assert.equal((await f.verify()).evaluationExecutionVerified,false);f.edit('controller/controller-receipt.json',v=>v.terminalRecheck.podUid='foreign');await assert.rejects(f.verify(),/terminal_recheck_unverified/);});
for(const [name,path,edit,reason]of [
 ['nonzero exit','controller/controller-receipt.json',v=>v.exit.exitCode=1,/controller_execution/],
 ['nonnumeric exit','controller/controller-receipt.json',v=>v.exit.exitCode='0',/controller_execution/],
 ['invalid timing','controller/controller-receipt.json',v=>v.finishedAt='unknown',/controller_timing/],
 ['generation outside controller','controller/controller-receipt.json',v=>v.finishedAt='2026-10-06T00:02:00Z',/controller_timing|generation_outside/],
 ['nonfinite host commit','controller/controller-receipt.json',v=>v.observations[0].sample.windows.commitFreeGiB=null,/host_resource/],
 ['failed resource guard','controller/controller-receipt.json',v=>v.observations[0].decision.allowed=false,/host_guard/],
 ['different container','controller/controller-receipt.json',v=>v.exit.containerID='containerd://'+ 'd'.repeat(64),/container_exit_identity/],
 ['restart container','controller/live-pod.json',v=>v.status.containerStatuses[0].restartCount=1,/container_exit_identity/],
 ['wrong image digest','controller/live-pod.json',v=>v.status.containerStatuses[0].imageID='other',/container_exit_identity/],
 ['unconfirmed termination','controller/controller-receipt.json',v=>v.terminationConfirmed=false,/controller_execution/],
 ['wrong Pod owner','controller/live-pod.json',v=>v.metadata.ownerReferences[0].uid='foreign',/job_pod_identity/],
 ['writable source','controller/live-pod.json',v=>v.spec.containers[0].volumeMounts.find(m=>m.name==='adapters').readOnly=false,/live_mount/],
 ['wrong source history','controller/controller-receipt.json',v=>v.inputs.sourceOptimizerHistoryUpdates=60,/input_scope/],
 ['modified runtime','controller/runtime-configmap.json',v=>v.data['evaluate-public-qa-fresh.py']+='changed',/runtime_hash/],
 ['unsealed response bytes','output/responses.json',v=>v.candidate.synthetic_0.content='modified',/output_artifact/],
 ['inventory omission','output/evaluation-receipt.json',v=>v.files.pop(),/output_inventory/],
 ['excluded samples','output/evaluation-receipt.json',v=>v.excludedRows=1,/execution_receipt/],
 ['inflated calls','output/evaluation-receipt.json',v=>v.modelCalls=512,/execution_receipt/],
 ['false completed state','output/evaluation-receipt.json',v=>v.state='error',/execution_receipt/],
 ['half precision','output/evaluation-receipt.json',v=>v.resources.precision='fp16',/generation_resources/],
 ['missing input binding','output/evaluation-receipt.json',v=>v.sourceTrainingExecutionVerified=false,/execution_receipt/],
 ['automatic quality claim','output/evaluation-receipt.json',v=>v.qualityClaimAllowed=true,/execution_receipt/],
])test('fresh verifier rejects '+name,async t=>{const f=fixture(t);f.edit(path,edit);await assert.rejects(f.verify(),reason);});
test('resealed response cannot substitute another prompt or adapter state',async t=>{for(const mutation of [v=>v.inputIdsSha256='a'.repeat(64),v=>v.promptSha256='b'.repeat(64),v=>v.adapterEnabled=false,v=>v.callOrdinal=128,v=>v.seconds=Infinity]){const f=fixture(t);mutation(f.responses.candidate.synthetic_0);const raw=f.put('output/responses.json',f.responses);f.receipt.responsesSha256=sha(raw);f.persist();await assert.rejects(f.verify(),/generation_(row|measurement)/);}});
test('sealed row artifacts still must exactly equal responses and ordered log records',async t=>{const f=fixture(t);f.edit('output/rows/candidate-synthetic_0.json',v=>v.content='substituted');f.persist();await assert.rejects(f.verify(),/generation_row_input/);const g=fixture(t);g.writeLog(g.logRows.slice(1));await assert.rejects(g.verify(),/sequential_lifecycle_order/);const h=fixture(t);[h.logRows[0],h.logRows[1]]=[h.logRows[1],h.logRows[0]];h.writeLog();await assert.rejects(h.verify(),/generation_log_sequence/);});
test('resealed resource and lifecycle evidence cannot hide OOM, unsupported adapter state or nonfinite timing',async t=>{for(const edit of [r=>r.modelLifecycle.sameLoadedBaseObject=false,r=>r.adapterStates.baseline.allAdapterModulesDisabled=false,r=>r.sideMeasurements.candidate.cgroup['memory.events'].oom='1',r=>r.sideMeasurements.candidate.generationSeconds=127,r=>r.sideMeasurements.candidate.wallSeconds=null]){const f=fixture(t);edit(f.receipt);f.persist();await assert.rejects(f.verify(),/lifecycle|adapter_execution_state|cgroup_oom|side_resources/);}});
test('production CLI rejects private-free synthetic inputs and never overwrites a report',t=>{const f=fixture(t),output=join(f.root,'report.json'),before=readFileSync(f.options.controllerReceipt),args=['scripts/verify-public-qa-fresh.mjs',f.options.runDirectory,f.options.controllerReceipt,output];const first=spawnSync(process.execPath,args,{encoding:'utf8'});assert.equal(first.status,2);const saved=readFileSync(output);assert.equal(JSON.parse(saved).evaluationExecutionVerified,false);assert.notEqual(spawnSync(process.execPath,args,{encoding:'utf8'}).status,0);assert.deepEqual(readFileSync(output),saved);assert.deepEqual(readFileSync(f.options.controllerReceipt),before);});



