import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,readdirSync,statSync,rmSync,unlinkSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,dirname,join} from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {verifyPublicQaGroundingFixture} from '../scripts/verify-public-qa-grounding.mjs';
import {verifyPublicQaGroundingContinuation,verifyPublicQaGroundingContinuationFixture,continuationPlan,verifyContinuationExposure,verifyRuntimeExitReconciliation} from '../scripts/verify-public-qa-grounding-continuation.mjs';
import {CONTINUATION_STAGE,CONTINUATION_SOURCE_FILES,SAMPLER} from '../scripts/prepare-public-qa-grounding-continuation.mjs';
import {QA_BASE_REVISION,QA_IMAGE,QA_NAMESPACE,QA_NODE,podSpec} from '../scripts/public-qa-workload.mjs';
import {STAGE2_DIAGNOSTIC_SOURCE_RUN} from '../scripts/public-qa-diagnostic-workload.mjs';
import {GROUNDING_STAGE} from '../scripts/prepare-public-qa-grounding.mjs';

const sha=value=>createHash('sha256').update(value).digest('hex');
function adapterBytes(value=.5){
 const header={__metadata__:{format:'pt'}},chunks=[];let offset=0;
 for(let layer=0;layer<32;layer++)for(const projection of ['q_proj','k_proj','v_proj','o_proj'])for(const side of ['A','B']){const chunk=Buffer.alloc(32);for(let index=0;index<8;index++)chunk.writeFloatLE(value,index*4);header[`base_model.model.model.layers.${layer}.self_attn.${projection}.lora_${side}.weight`]={dtype:'F32',shape:side==='A'?[8,1]:[1,8],data_offsets:[offset,offset+32]};offset+=32;chunks.push(chunk);}
 const headerBytes=Buffer.from(JSON.stringify(header)),prefix=Buffer.alloc(8);prefix.writeBigUInt64LE(BigInt(headerBytes.length));return Buffer.concat([prefix,headerBytes,...chunks]);
}
function previousFixture(t){
 const root=mkdtempSync(join(tmpdir(),'evidscope-grounding-verifier-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const runId='public-qa-grounding-test',runDirectory=resolve(root,'output'),controllerReceipt=resolve(root,'controller/controller-receipt.json');
 const put=(name,value,bom=false)=>{const path=resolve(root,name);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,Buffer.isBuffer(value)?value:(bom?'\uFEFF':'')+(typeof value==='string'?value:JSON.stringify(value)));return readFileSync(path);};
 const get=name=>JSON.parse(readFileSync(resolve(root,name),'utf8').replace(/^\uFEFF/,''));
 const edit=(name,change)=>{const value=get(name);change(value);put(name,value);};
 const inventory=directory=>readdirSync(resolve(root,directory)).filter(name=>!name.endsWith('-complete.json')).sort().map(path=>({path,bytes:statSync(resolve(root,directory,path)).size,sha256:sha(readFileSync(resolve(root,directory,path)))}));
 const trainingPins={},datasetPins={},runtimeData=Object.fromEntries(['train-public-qa.py','train-foundation-lora.py','training_artifacts.py','resource-pilot.py','public_qa_cuda_runtime.py','public_qa_memory_gate.py','public_qa_kbit.py','public_qa_thermal.py','public_qa_resume.py','public_qa_grounding.py'].map(name=>[name,`# synthetic ${name}\n`])),runtimeSha256=sha(JSON.stringify(runtimeData)),runtimeConfigMap='public-qa-grounding-'+runtimeSha256.slice(0,16),runtimeFiles=Object.fromEntries(Object.entries(runtimeData).map(([name,value])=>[name,sha(value)]));
 trainingPins.artifactLockSha256=sha(put('source/lock.json',{revision:QA_BASE_REVISION}));
 const sourceIdentity={baseRepository:'fdtn-ai/Foundation-Sec-8B-Reasoning',baseRevision:QA_BASE_REVISION,baseArtifactLockSha256:trainingPins.artifactLockSha256,rank:8,sequenceLength:1024,batchSize:1,gradientAccumulationSteps:16,maxSteps:40,stage:'public_qa_stage2'};
 put('source/candidate/adapter_config.json',{r:8});put('source/candidate/adapter_model.safetensors','synthetic source adapter');put('source/candidate/training-receipt.json',{identity:sourceIdentity,globalStep:40});
 trainingPins.candidateMarkerSha256=sha(put('source/candidate/candidate-complete.json',{schemaVersion:1,identity:sourceIdentity,globalStep:40,files:inventory('source/candidate')}));
 trainingPins.adapterSha256=sha(readFileSync(resolve(root,'source/candidate/adapter_model.safetensors')));
 trainingPins.sourceControllerSha256=sha(put('source/controller.json',{runId:STAGE2_DIAGNOSTIC_SOURCE_RUN,mode:'explicit_public_human_qa_stage2',state:'process_completed',exit:{exitCode:0},terminationConfirmed:true}));
 trainingPins.sourceRuntimeConfigMapSha256=sha(put('source/runtime.json',{data:{fixture:'historic source trainer differs from current workspace'}}));
 trainingPins.sourceVerificationSha256=sha(put('source/verification.json',{verified:true,runId:STAGE2_DIAGNOSTIC_SOURCE_RUN,trainingRunCompleted:true,terminationConfirmed:true,globalStep:40,actualOptimizerUpdates:40,skippedOptimizerUpdates:0,qualityClaimAllowed:false,promotionAllowed:false,artifactSha256:trainingPins.candidateMarkerSha256,controllerSha256:trainingPins.sourceControllerSha256,runtimeConfigMapSha256:trainingPins.sourceRuntimeConfigMapSha256,identity:sourceIdentity}));
 const sourceRows=Array.from({length:704},(_,index)=>{const isImpossible=index%2===1,context=`정답 ${index}`,question=`질문 ${index}`,answers=isImpossible?[]:[{text:'정답',answer_start:0}];return {id:`row-${index}`,familyId:`family-${index}`,contextSha256:sha(context),context,question,answers,isImpossible,split:index<640?'train':'validation',originalQa:{question,answers,is_impossible:isImpossible}};});
 const lineRows=rows=>rows.map(JSON.stringify).join('\n')+'\n';
 const sourceFiles={sourceManifest:'source-manifest.json',sourceTrain:'source-train.jsonl',sourceValidation:'source-validation.jsonl',oldTraining:'old-training.jsonl',diagnostic:'diagnostic.jsonl'};
 datasetPins.sourceManifest=sha(put('data/source-manifest.json',{revision:'3efd98708a40ff49251fddde35453f8fbb11f536',license:'CC-BY-SA-4.0'}));
 datasetPins.sourceTrain=sha(put('data/source-train.jsonl',lineRows(sourceRows.slice(0,640))));datasetPins.sourceValidation=sha(put('data/source-validation.jsonl',lineRows(sourceRows.slice(640))));
 const excluded={id:'excluded',familyId:'excluded-family',contextSha256:sha('excluded')};datasetPins.oldTraining=sha(put('data/old-training.jsonl',lineRows([excluded])));datasetPins.diagnostic=sha(put('data/diagnostic.jsonl',lineRows([excluded])));
 const dataset=sourceRows.map(row=>({...row,stage:GROUNDING_STAGE,contextSelection:'full_original_context',localHumanReviewPerformed:false,privacyScreen:{kind:'basic_email_mobile_resident_id_regex',passed:true,comprehensivePrivacyReview:false}})),datasetSha256=sha(put('data/data.jsonl',lineRows(dataset)));
 const manifest={schemaVersion:1,stage:GROUNDING_STAGE,task:'korean_extractive_qa',datasetSha256,upstreamRevision:'3efd98708a40ff49251fddde35453f8fbb11f536',license:'CC-BY-SA-4.0',sourcePins:datasetPins,sourceFiles,counts:{train:640,validation:64},labelCounts:{train:{answerable:320,impossible:320},validation:{answerable:32,impossible:32}},heldoutUsed:false,localHumanReviewPerformed:false,qualityClaimAllowed:false,promotionAllowed:false,selection:{maxContextCodepoints:650,fullContextPreserved:true,answerBasedCropping:false,actualTokenizerPreadmissionRequired:true},previousExposureOverlap:{id:0,family:0,context:0},rowIds:dataset.map(row=>row.id)},manifestSha256=sha(put('data/manifest.json',manifest));
 const identity={baseRepository:'fdtn-ai/Foundation-Sec-8B-Reasoning',baseRevision:QA_BASE_REVISION,baseArtifactLockSha256:trainingPins.artifactLockSha256,datasetSha256,manifestSha256,trainerSha256:runtimeFiles['train-public-qa.py'],artifactHelperSha256:runtimeFiles['training_artifacts.py'],bindingHelperSha256:runtimeFiles['train-foundation-lora.py'],groundingHelperSha256:runtimeFiles['public_qa_grounding.py'],image:QA_IMAGE,stage:GROUNDING_STAGE,contextSelection:'full_original_context',precision:'bf16',modelDtype:'bfloat16',quantComputeDtype:'bfloat16',rank:8,sequenceLength:1024,batchSize:1,gradientAccumulationSteps:16,seed:42,learningRate:.0001,maxSteps:20,gpuMemoryFraction:.65};
 const provenance={schemaVersion:1,kind:'adapter_only_warmstart_new_balanced_public_qa',sourceRunId:STAGE2_DIAGNOSTIC_SOURCE_RUN,sourceGlobalStep:40,sourcePins:{marker:trainingPins.candidateMarkerSha256,adapter:trainingPins.adapterSha256,controller:trainingPins.sourceControllerSha256,verification:trainingPins.sourceVerificationSha256},sourceIdentity,targetRunId:runId,targetIdentity:identity,optimizerReset:true,schedulerReset:true,targetOptimizerSteps:20,sourceTrainingExecutionVerified:true,qualityClaimAllowed:false,promotionAllowed:false},provenanceSha256=sha(put('data/provenance.json',provenance));
 const inputs={...trainingPins,sourceRunId:STAGE2_DIAGNOSTIC_SOURCE_RUN,sourceController:'source/controller.json',sourceVerification:'source/verification.json',sourceRuntime:'source/runtime.json',candidateMarker:'source/candidate/candidate-complete.json',adapter:'source/candidate/adapter_model.safetensors',lock:'source/lock.json',data:'data/data.jsonl',manifest:'data/manifest.json',datasetSha256,manifestSha256,mode:'explicit_public_human_qa_grounding',stage:GROUNDING_STAGE,diagnosticOnly:false,rows:704,runId,qualityClaimAllowed:false,promotionAllowed:false,runtimeConfigMap,runtimeSha256,runtimeFiles,targetIdentity:identity,provenancePath:'data/provenance.json',provenanceSha256,groundingProvenance:provenance};
 put('controller/runtime-configmap.json',{apiVersion:'v1',kind:'ConfigMap',immutable:true,metadata:{name:runtimeConfigMap,namespace:QA_NAMESPACE,annotations:{'evidscope.io/code-sha256':runtimeSha256}},data:runtimeData},true);
 const spec=podSpec({gpu:true}),container=spec.containers[0];
 spec.volumes=spec.volumes.filter(volume=>volume.name!=='checkpoints');container.volumeMounts=container.volumeMounts.filter(mount=>mount.name!=='checkpoints');Object.assign(container.volumeMounts.find(mount=>mount.name==='data'),{mountPath:'/data/grounding',subPath:`grounding/${runId}`});
 spec.volumes.push({name:'warmstart',persistentVolumeClaim:{claimName:'public-qa-checkpoints',readOnly:true}},{name:'grounding-output',persistentVolumeClaim:{claimName:'public-qa-checkpoints'}},{name:'runtime',configMap:{name:runtimeConfigMap}});container.volumeMounts.push({name:'warmstart',mountPath:'/warmstart/candidate',subPath:`runs/${STAGE2_DIAGNOSTIC_SOURCE_RUN}/candidate`,readOnly:true},{name:'grounding-output',mountPath:'/checkpoints/runs',subPath:'grounding-runs',readOnly:false},{name:'runtime',mountPath:'/runtime',readOnly:true});
 container.command=['python','/runtime/train-public-qa.py'];container.args=['--data','/data/grounding/data.jsonl','--manifest','/data/grounding/manifest.json','--grounding-provenance','/data/grounding/provenance.json','--warmstart-adapter','/warmstart/candidate','--model-dir','/models/foundation-base','--base-revision',QA_BASE_REVISION,'--output',`/checkpoints/runs/${runId}`,'--max-steps','20'];
 container.env=Object.entries({PYTHONPATH:'/runtime',EVIDSCOPE_ISOLATED:'1',EVIDSCOPE_MEMORY_HIGH_REQUIRED:'1',EVIDSCOPE_GROUNDING_PROVENANCE_SHA256:provenanceSha256,EVIDSCOPE_DATASET_SHA256:datasetSha256,EVIDSCOPE_BASE_REPOSITORY:'fdtn-ai/Foundation-Sec-8B-Reasoning',EVIDSCOPE_BASE_REVISION:QA_BASE_REVISION,EVIDSCOPE_BASE_ARTIFACT_LOCK_SHA256:trainingPins.artifactLockSha256,EVIDSCOPE_TRAINING_IMAGE:QA_IMAGE}).map(([name,value])=>({name,value}));
 const job={metadata:{name:runId,namespace:QA_NAMESPACE,annotations:{'evidscope.io/run-kind':'explicit-public-human-qa-grounding','evidscope.io/dataset-sha256':datasetSha256,'evidscope.io/manifest-sha256':manifestSha256,'evidscope.io/provenance-sha256':provenanceSha256}},spec:{template:{spec}}},liveSpec={...structuredClone(spec),nodeName:QA_NODE},jobUid='synthetic-job-uid',podUid='synthetic-pod-uid',podName=runId+'-pod';
 const controller={schemaVersion:1,runId,jobUid,podUid,podName,mode:'explicit_public_human_qa_grounding_v1',state:'process_completed',exit:{exitCode:0},terminationConfirmed:true,admission:{allowed:true},trainingRunCompleted:false,qualityClaimAllowed:false,promotionAllowed:false,automaticGovernanceGateClaimed:false,inputs,manifest:job,manifestSha256:sha(JSON.stringify(job)),livePodSpec:liveSpec,memoryHigh:{podUid,markerReleased:true,containerLeafOnly:true,memoryHigh:'2147483648',memoryMax:'12884901888'}};
 put('controller/controller-receipt.json',controller,true);put('controller/live-job.json',{metadata:{name:runId,namespace:QA_NAMESPACE,uid:jobUid},spec:{template:{spec}}});put('controller/live-pod.json',{metadata:{name:podName,namespace:QA_NAMESPACE,uid:podUid,ownerReferences:[{name:runId,uid:jobUid,kind:'Job'}]},spec:liveSpec});
 const lineage={...provenance,provenanceSha256,sourceOptimizerUpdates:40,optimizerUpdatesThisExperiment:20,sourceStateLoaded:'adapter_only',optimizerStateLoaded:false,schedulerStateLoaded:false},metrics={train_loss:.4,eval_loss:.5,base_eval_loss:1.2};
 const receipt={schemaVersion:2,status:'trained_'+GROUNDING_STAGE,globalStep:20,identity,trainingMetrics:metrics,trainingRunCompleted:true,qualityClaimAllowed:false,promotionAllowed:false,heldOutTestUsedForTraining:false,localHumanReviewPerformed:false,sourceLicense:'CC-BY-SA-4.0',targetFormat:'exact_human_answer_json_without_generated_reasoning',groundingLineage:lineage,cudaPeakAllocatedBytes:100,cudaPeakReservedBytes:200,adapterFiniteCheck:{passed:true,tensorCount:256,nonFiniteTensorCount:0,dtypes:['torch.float32'],beforeCandidateSealing:true}};
 put('output/candidate/adapter_config.json',{r:8});put('output/candidate/adapter_model.safetensors',adapterBytes());put('output/candidate/training-receipt.json',receipt);
 const sealCandidate=()=>put('output/candidate/candidate-complete.json',{schemaVersion:1,globalStep:20,identity,metrics,files:inventory('output/candidate')});sealCandidate();
 for(const step of [10,20]){const directory='output/checkpoint-'+step;for(const name of ['adapter_config.json','optimizer.pt','scheduler.pt','rng_state.pth','training_args.bin'])put(directory+'/'+name,`synthetic ${step} ${name}`);put(directory+'/adapter_model.safetensors',adapterBytes(step===20?.5:.25));put(directory+'/trainer_state.json',{global_step:step});put(directory+'/checkpoint-complete.json',{schemaVersion:1,globalStep:step,identity,files:inventory(directory)});}
 put('output/encoding-receipt.json',{datasetSha256,rows:dataset.map(row=>({id:row.id,contextStart:0,contextEnd:Array.from(row.context).length,tokens:100,answerPreserved:true,originalContextSha256:row.contextSha256,selectedContextSha256:row.contextSha256}))});
 const records=Array.from({length:20},(_,index)=>({optimizerStep:index+1,actualOptimizerUpdates:index+1,skippedOptimizerUpdates:0,learningRate:.0001*(19-index)/20,cudaPeakAllocatedBytes:100,cudaPeakReservedBytes:200}));
 const writeLog=(steps=records)=>put('controller/training.log',JSON.stringify({groundingWarmstart:{...lineage,optimizerUpdatesThisExperiment:0}})+'\n'+JSON.stringify({groundingAdapterLoaded:true,sourceGlobalStep:40,newGlobalStep:0,optimizerStateLoaded:false,schedulerStateLoaded:false})+'\n'+steps.map(value=>'progress bar '+JSON.stringify(value)).join('\n')+'\n'+JSON.stringify({adapterFiniteCheck:receipt.adapterFiniteCheck})+'\n'+JSON.stringify(receipt)+'\n');writeLog();
 const options={runDirectory,controllerReceipt,workspaceRoot:root},pins={training:trainingPins,dataset:datasetPins};
 return {root,put,get,edit,options,pins,receipt,identity,lineage,records,writeLog,sealCandidate,verify:()=>verifyPublicQaGroundingFixture(options,pins)};
}

const canonical=value=>JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(key=>[key,item[key]])):item);
function fixture(t){
 const f=previousFixture(t),runId='public-qa-grounding-test',sourceRunId='public-qa-grounding-20261005-r4',get=f.get,put=f.put;
 const sourceIdentity=structuredClone(f.identity),sourcePins={};
 const inventory=directory=>readdirSync(resolve(f.root,directory)).filter(name=>!name.endsWith('-complete.json')).sort().map(path=>({path,bytes:statSync(resolve(f.root,directory,path)).size,sha256:sha(readFileSync(resolve(f.root,directory,path)))}));
 for(const name of ['adapter_config.json','adapter_model.safetensors','training-receipt.json'])put('continuation-source/candidate/'+name,readFileSync(resolve(f.root,'output/candidate/'+name)));
 sourcePins.candidateMarkerSha256=sha(put('continuation-source/candidate/candidate-complete.json',{schemaVersion:1,globalStep:20,identity:sourceIdentity,files:inventory('continuation-source/candidate')}));
 sourcePins.adapterSha256=sha(readFileSync(resolve(f.root,'continuation-source/candidate/adapter_model.safetensors')));
 sourcePins.sourceControllerSha256=sha(put('continuation-source/controller.json',{schemaVersion:1,runId:sourceRunId,mode:'explicit_public_human_qa_grounding_v1',state:'process_completed',exit:{exitCode:0},terminationConfirmed:true}));
 const sourceRuntimeHash=sha(put('continuation-source/runtime.json',get('controller/runtime-configmap.json')));
 sourcePins.sourceProvenanceSha256=sha(put('continuation-source/provenance.json',{fixture:'previous pinned provenance'}));
 sourcePins.sourceVerificationSha256=sha(put('continuation-source/verification.json',{schemaVersion:1,verificationPassed:true,verified:true,syntheticFixture:false,actualTrainingExecutionVerified:true,sourceTrainingExecutionVerified:true,trainingRunCompleted:true,terminationConfirmed:true,runId:sourceRunId,globalStep:20,actualOptimizerUpdates:20,sourceOptimizerUpdates:40,totalAdapterHistoryOptimizerUpdates:60,skippedOptimizerUpdates:0,qualityClaimAllowed:false,promotionAllowed:false,artifactSha256:sourcePins.candidateMarkerSha256,adapterSha256:sourcePins.adapterSha256,controllerSha256:sourcePins.sourceControllerSha256,runtimeConfigMapSha256:sourceRuntimeHash,identity:sourceIdentity}));
 const dataset=get('data/manifest.json').rowIds.map((id,index)=>{const isImpossible=index<640?index>=440:index%2===1,context=`정답 ${index}`,question=`질문 ${index}`,answers=isImpossible?[]:[{text:'정답',answer_start:0}];return {id,familyId:'family-'+index,contextSha256:sha(context),context,question,answers,isImpossible,split:index<640?'train':'validation',originalQa:{question,answers,is_impossible:isImpossible}};});
 const lineRows=rows=>rows.map(JSON.stringify).join('\n')+'\n',datasetPins={...f.pins.dataset};
 datasetPins.sourceTrain=sha(put('data/source-train.jsonl',lineRows(dataset.slice(0,640))));datasetPins.sourceValidation=sha(put('data/source-validation.jsonl',lineRows(dataset.slice(640))));datasetPins.previousGrounding=sha(put('data/previous-grounding.jsonl',lineRows([{id:'previous',familyId:'previous-family',contextSha256:sha('previous')}])));
 const decorated=dataset.map(row=>({...row,stage:CONTINUATION_STAGE,contextSelection:'full_original_context',localHumanReviewPerformed:false,privacyScreen:{kind:'basic_email_mobile_resident_id_regex',passed:true,comprehensivePrivacyReview:false}}));
 const dataHash=sha(put('data/data.jsonl',lineRows(decorated))),manifest=get('data/manifest.json');Object.assign(manifest,{stage:CONTINUATION_STAGE,datasetSha256:dataHash,sourcePins:datasetPins,sourceFiles:CONTINUATION_SOURCE_FILES,labelCounts:{train:{answerable:440,impossible:200},validation:{answerable:32,impossible:32}},sampler:SAMPLER});const manifestHash=sha(put('data/manifest.json',manifest));
 const runtime=get('controller/runtime-configmap.json');runtime.data['public_qa_grounding_kbit.py']='# synthetic kbit helper\n';runtime.data['public_qa_grounding_continuation.py']='# synthetic continuation helper\n';const runtimeHash=sha(JSON.stringify(runtime.data)),runtimeName='public-qa-gcont-'+runtimeHash.slice(0,16),runtimeFiles=Object.fromEntries(Object.entries(runtime.data).map(([key,value])=>[key,sha(value)]));runtime.metadata.name=runtimeName;runtime.metadata.annotations['evidscope.io/code-sha256']=runtimeHash;put('controller/runtime-configmap.json',runtime);
 const identity={...f.identity,stage:CONTINUATION_STAGE,datasetSha256:dataHash,manifestSha256:manifestHash,learningRate:.00003,sampler:SAMPLER,groundingHelperSha256:runtimeFiles['public_qa_grounding_continuation.py']};
 const provenance={schemaVersion:1,kind:'adapter_only_warmstart_stratified_public_qa_continuation',sourceRunId,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:60,sourcePins:{marker:sourcePins.candidateMarkerSha256,adapter:sourcePins.adapterSha256,controller:sourcePins.sourceControllerSha256,verification:sourcePins.sourceVerificationSha256,provenance:sourcePins.sourceProvenanceSha256},sourceIdentity,targetRunId:runId,targetIdentity:identity,optimizerReset:true,schedulerReset:true,targetOptimizerSteps:20,sourceTrainingExecutionVerified:true,qualityClaimAllowed:false,promotionAllowed:false};const provenanceHash=sha(put('data/provenance.json',provenance));
 const controller=get('controller/controller-receipt.json');Object.assign(controller.inputs,{...sourcePins,sourceRunId,sourceController:'continuation-source/controller.json',sourceVerification:'continuation-source/verification.json',sourceProvenance:'continuation-source/provenance.json',candidateMarker:'continuation-source/candidate/candidate-complete.json',adapter:'continuation-source/candidate/adapter_model.safetensors',sourceRuntime:'continuation-source/runtime.json',sourceRuntimeConfigMapSha256:sourceRuntimeHash,mode:'explicit_public_human_qa_grounding_continuation',stage:CONTINUATION_STAGE,datasetSha256:dataHash,manifestSha256:manifestHash,targetIdentity:identity,groundingProvenance:provenance,provenanceSha256:provenanceHash,runtimeConfigMap:runtimeName,runtimeSha256:runtimeHash,runtimeFiles});controller.mode='explicit_public_human_qa_grounding_continuation_v1';
 const updateSpec=spec=>{const c=spec.containers[0];Object.assign(c.volumeMounts.find(m=>m.name==='data'),{subPath:`grounding-continuation/${runId}`});c.volumeMounts.find(m=>m.name==='warmstart').subPath=`grounding-runs/${sourceRunId}/candidate`;c.volumeMounts.find(m=>m.name==='grounding-output').subPath='grounding-continuation-runs';spec.volumes.find(v=>v.name==='runtime').configMap.name=runtimeName;c.env.find(e=>e.name==='EVIDSCOPE_GROUNDING_PROVENANCE_SHA256').value=provenanceHash;c.env.find(e=>e.name==='EVIDSCOPE_DATASET_SHA256').value=dataHash;};
 updateSpec(controller.manifest.spec.template.spec);updateSpec(controller.livePodSpec);Object.assign(controller.manifest.metadata.annotations,{'evidscope.io/run-kind':'explicit-public-human-qa-grounding-continuation','evidscope.io/dataset-sha256':dataHash,'evidscope.io/manifest-sha256':manifestHash,'evidscope.io/provenance-sha256':provenanceHash});controller.manifest.spec.backoffLimit=0;controller.manifest.spec.activeDeadlineSeconds=3600;controller.manifestSha256=sha(JSON.stringify(controller.manifest));put('controller/controller-receipt.json',controller);
 f.edit('controller/live-job.json',job=>updateSpec(job.spec.template.spec));f.edit('controller/live-pod.json',pod=>updateSpec(pod.spec));
 const encoding={datasetSha256:dataHash,rows:decorated.map(row=>({id:row.id,contextStart:0,contextEnd:Array.from(row.context).length,tokens:100,answerPreserved:true,originalContextSha256:row.contextSha256,selectedContextSha256:row.contextSha256,inputSha256:sha(row.id+' synthetic flat encoded arrays')}))};put('output/encoding-receipt.json',encoding);
 const plan=continuationPlan(decorated),plannedOrderSha256=sha(canonical(plan));
 const exposure=step=>({schemaVersion:1,stage:CONTINUATION_STAGE,datasetSha256:dataHash,sourceOptimizerHistoryUpdates:60,optimizerUpdatesThisExperiment:step,totalAdapterHistoryOptimizerUpdates:60+step,sampler:SAMPLER,plannedOrderSha256,processedMicrobatches:step*16,completedOptimizerGroups:step,counts:{answerable:step*11,impossible:step*5},groups:Array.from({length:step},(_,index)=>({optimizerGroup:index+1,microbatches:16,answerable:11,impossible:5})),rows:plan.slice(0,step*16).map((record,index)=>({...record,microbatch:index+1,optimizerGroup:Math.floor(index/16)+1,positionInGroup:index%16+1,inputSha256:encoding.rows[record.datasetIndex].inputSha256,tokenCount:100,forwardBackwardCompleted:true})),qualityClaimAllowed:false,promotionAllowed:false});
 const latest=exposure(20),exposureRaw=put('output/training-exposure.json',latest),lineage={...provenance,provenanceSha256:provenanceHash,sourceOptimizerUpdates:60,optimizerUpdatesThisExperiment:20,sourceStateLoaded:'adapter_only',optimizerStateLoaded:false,schedulerStateLoaded:false};
 const receipt={...f.receipt,status:'trained_'+CONTINUATION_STAGE,identity,groundingLineage:lineage,sourceOptimizerHistoryUpdates:60,optimizerUpdatesThisExperiment:20,totalAdapterHistoryOptimizerUpdates:80,trainingExposure:{path:'training-exposure.json',sha256:sha(exposureRaw),processedMicrobatches:320,completedOptimizerGroups:20,counts:{answerable:220,impossible:100},sourceOptimizerHistoryUpdates:60,optimizerUpdatesThisExperiment:20,totalAdapterHistoryOptimizerUpdates:80,actualTensorBindingChecked:true}};
 put('output/candidate/adapter_model.safetensors',adapterBytes(.75));put('output/candidate/training-receipt.json',receipt);put('output/candidate/training-exposure.json',exposureRaw);
 const sealCandidate=()=>put('output/candidate/candidate-complete.json',{schemaVersion:1,globalStep:20,identity,metrics:receipt.trainingMetrics,files:inventory('output/candidate')});sealCandidate();
 const sealCheckpoint=step=>put(`output/checkpoint-${step}/checkpoint-complete.json`,{schemaVersion:1,globalStep:step,identity,files:inventory(`output/checkpoint-${step}`)});
 for(const step of [10,20]){put(`output/checkpoint-${step}/adapter_model.safetensors`,adapterBytes(step===20?.75:.6));put(`output/checkpoint-${step}/training-exposure.json`,exposure(step));sealCheckpoint(step);}
 const records=f.records.map(record=>({...record,learningRate:record.learningRate*.3}));
 const writeLog=(steps=records,consumed=latest.rows,groups=latest.groups)=>put('controller/training.log',[{groundingWarmstart:{...lineage,optimizerUpdatesThisExperiment:0}},{groundingAdapterLoaded:true,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:60,newGlobalStep:0,optimizerStateLoaded:false,schedulerStateLoaded:false},...Array.from({length:20},(_,index)=>[...consumed.slice(index*16,(index+1)*16).map(record=>({continuationTrainingSample:record})),...(steps[index]?[steps[index]]:[]),...(groups[index]?[{continuationOptimizerGroup:groups[index],processedMicrobatches:groups[index].optimizerGroup*16,totalAdapterHistoryOptimizerUpdates:60+groups[index].optimizerGroup}]:[])]).flat(),{adapterFiniteCheck:receipt.adapterFiniteCheck},receipt].map(JSON.stringify).join('\n')+'\n');writeLog();
 return {...f,pins:{training:sourcePins,dataset:datasetPins},identity,receipt,lineage,dataset:decorated,encoding,exposure:latest,records,writeLog,sealCandidate,sealCheckpoint,verify:()=>verifyPublicQaGroundingContinuationFixture(f.options,{training:sourcePins,dataset:datasetPins})};
}

test('continuation fixture binds 20 fresh updates and 220/100 actually consumed samples without execution claims',async t=>{
 const f=fixture(t),proof=await f.verify();assert.equal(proof.verificationPassed,true);assert.equal(proof.syntheticFixture,true);assert.equal(proof.verified,false);assert.equal(proof.actualTrainingExecutionVerified,false);assert.equal(proof.trainingRunCompleted,false);assert.equal(proof.sourceOptimizerUpdates,60);assert.equal(proof.sourceGlobalStep,20);assert.equal(proof.totalAdapterHistoryOptimizerUpdates,80);assert.equal(proof.optimizerStateRestored,false);assert.deepEqual(proof.trainingExposure.counts,{answerable:220,impossible:100});assert.equal(proof.trainingExposure.processedMicrobatches,320);assert.equal(proof.qualityClaimAllowed,false);assert.equal(proof.promotionAllowed,false);await assert.rejects(verifyPublicQaGroundingContinuation(f.options),/source_pin_changed/);
});
test('the production verifier refuses fixture pins and never overwrites existing reports',async t=>{
 const f=fixture(t),path=join(f.root,'verification.json'),before=readFileSync(f.options.controllerReceipt),run=spawnSync(process.execPath,['scripts/verify-public-qa-grounding-continuation.mjs',f.options.runDirectory,f.options.controllerReceipt,path],{encoding:'utf8'});assert.equal(run.status,2,run.stderr);const report=readFileSync(path);assert.equal(JSON.parse(report).actualTrainingExecutionVerified,false);assert.deepEqual(readFileSync(f.options.controllerReceipt),before);assert.notEqual(spawnSync(process.execPath,['scripts/verify-public-qa-grounding-continuation.mjs',f.options.runDirectory,f.options.controllerReceipt,path],{encoding:'utf8'}).status,0);assert.deepEqual(readFileSync(path),report);
});
for(const [name,path,edit,reason]of [
 ['nonzero execution','controller/controller-receipt.json',v=>v.exit.exitCode=1,/controller_execution/],
 ['missing termination','controller/controller-receipt.json',v=>v.terminationConfirmed=false,/controller_execution/],
 ['source history inflated to optimizer step eighty','continuation-source/verification.json',v=>v.globalStep=80,/source_file_changed/],
 ['source bytes changed','continuation-source/candidate/candidate-complete.json',v=>v.globalStep=21,/source_file_changed/],
 ['writable warmstart','controller/live-pod.json',v=>v.spec.containers[0].volumeMounts.find(m=>m.name==='warmstart').readOnly=false,/mounts_changed/],
 ['foreign Pod owner','controller/live-pod.json',v=>v.metadata.ownerReferences[0].uid='foreign',/job_pod_binding/],
 ['GPU limit removed','controller/live-pod.json',v=>delete v.spec.containers[0].resources.limits['nvidia.com/gpu'],/resources_changed/],
 ['wrong memory leaf','controller/controller-receipt.json',v=>v.memoryHigh.podUid='foreign',/memory_control/],
 ['new runtime changed','controller/runtime-configmap.json',v=>v.data['public_qa_grounding_continuation.py']+='changed',/runtime_changed/],
 ['missing forward/backward','output/training-exposure.json',v=>v.rows[0].forwardBackwardCompleted=false,/consumed_row_changed/],
 ['different encoded tensor','output/training-exposure.json',v=>v.rows[0].inputSha256='f'.repeat(64),/tensor_binding_changed/],
 ['duplicate microbatch','output/training-exposure.json',v=>v.rows[1]=v.rows[0],/consumed_row_changed/],
 ['full dataset instead of consumed prefix','output/training-exposure.json',v=>v.processedMicrobatches=640,/exposure_steps/],
 ['incorrect 50/50 group','output/training-exposure.json',v=>v.groups[0].answerable=8,/exposure_balance/],
 ['token cropping','output/encoding-receipt.json',v=>v.rows[0].contextStart=1,/full_context_encoding/],
])test('continuation rejects '+name,async t=>{const f=fixture(t);f.edit(path,edit);await assert.rejects(f.verify(),reason);});
test('observed sample order cannot be substituted by a self-consistent arbitrary sampler plan',async t=>{const f=fixture(t),changed=structuredClone(f.exposure);changed.rows.reverse();assert.throws(()=>verifyContinuationExposure(changed,f.dataset,f.encoding,20),/consumed_row_changed/);changed.rows=f.exposure.rows;changed.plannedOrderSha256='b'.repeat(64);assert.throws(()=>verifyContinuationExposure(changed,f.dataset,f.encoding,20),/identity_changed/);});
test('ordered optimizer and reverse-pass records are independently required',async t=>{const f=fixture(t);f.writeLog(f.records.slice(1));await assert.rejects(f.verify(),/actual_optimizer_updates/);f.writeLog(f.records,f.exposure.rows.slice(1));await assert.rejects(f.verify(),/exposure_log/);f.writeLog(f.records,f.exposure.rows,f.exposure.groups.slice(1));await assert.rejects(f.verify(),/exposure_log/);f.writeLog(f.records.map(r=>({...r,skippedOptimizerUpdates:1})));await assert.rejects(f.verify(),/actual_optimizer_updates/);});
test('optimizer confirmation cannot precede its sixteen completed reverse passes',async t=>{const f=fixture(t),lines=readFileSync(resolve(f.root,'controller/training.log'),'utf8').trim().split('\n'),at=lines.findIndex(line=>line.startsWith('{"optimizerStep":1,')),[confirmation]=lines.splice(at,1);lines.splice(2,0,confirmation);f.put('controller/training.log',lines.join('\n')+'\n');await assert.rejects(f.verify(),/exposure_optimizer_order/);});
test('resealed source evidence cannot conceal an unverified training history',async t=>{const f=fixture(t);f.edit('continuation-source/verification.json',v=>v.totalAdapterHistoryOptimizerUpdates=61);f.pins.training.sourceVerificationSha256=sha(readFileSync(resolve(f.root,'continuation-source/verification.json')));f.edit('controller/controller-receipt.json',v=>v.inputs.sourceVerificationSha256=f.pins.training.sourceVerificationSha256);await assert.rejects(f.verify(),/source_training_unverified/);});
test('checkpoint exposure and final adapter are sealed and cannot be replaced',async t=>{const f=fixture(t);f.edit('output/checkpoint-10/training-exposure.json',v=>v.rows[0].inputSha256='f'.repeat(64));await assert.rejects(f.verify(),/checkpoint_artifact_changed/);f.sealCheckpoint(10);await assert.rejects(f.verify(),/tensor_binding_changed/);const g=fixture(t);g.put('output/checkpoint-20/adapter_model.safetensors',adapterBytes(.85));g.sealCheckpoint(20);await assert.rejects(g.verify(),/final_checkpoint_adapter/);});
test('finite and distinct new adapter bytes are mandatory',async t=>{const f=fixture(t);const raw=adapterBytes(NaN);f.put('output/candidate/adapter_model.safetensors',raw);f.sealCandidate();f.put('output/checkpoint-20/adapter_model.safetensors',raw);f.sealCheckpoint(20);await assert.rejects(f.verify(),/adapter_nonfinite_tensor/);const g=fixture(t);g.put('output/candidate/adapter_model.safetensors',adapterBytes());g.sealCandidate();g.put('output/checkpoint-20/adapter_model.safetensors',adapterBytes());g.sealCheckpoint(20);await assert.rejects(g.verify(),/final_checkpoint_adapter/);});
test('source family overlap cannot be hidden by repinning synthetic dataset source receipts',async t=>{const f=fixture(t);f.put('data/previous-grounding.jsonl',JSON.stringify({id:'previous',familyId:f.dataset[0].familyId,contextSha256:sha('previous')})+'\n');f.pins.dataset.previousGrounding=sha(readFileSync(resolve(f.root,'data/previous-grounding.jsonl')));f.edit('data/manifest.json',v=>v.sourcePins.previousGrounding=f.pins.dataset.previousGrounding);f.edit('controller/controller-receipt.json',v=>v.inputs.manifestSha256=sha(readFileSync(resolve(f.root,'data/manifest.json'))));await assert.rejects(f.verify(),/previous_exposure_leakage/);});

function runtimeExitFixture(t){
 const f=fixture(t),cid='a'.repeat(64),attempt='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
 const command="import json,pathlib; p=pathlib.Path('/sys/fs/cgroup'); e=dict(l.split() for l in (p/'memory.events').read_text().splitlines()); print(json.dumps({'memoryCurrentGiB':int((p/'memory.current').read_text())/1073741824,'memoryLimitGiB':int((p/'memory.max').read_text())/1073741824,'oomCount':int(e.get('oom',0)),'oomKillCount':int(e.get('oom_kill',0)),'cpuMax':(p/'cpu.max').read_text().strip(),'memoryStat':dict((k,int(v)) for k,v in (line.split() for line in (p/'memory.stat').read_text().splitlines()) if k in ('anon','file','file_mapped','file_dirty','inactive_file','active_file'))}))";
 f.edit('controller/controller-receipt.json',v=>{v.state='error';delete v.exit;v.startedAt='2026-10-06T00:00:00.000Z';v.finishedAt='2026-10-06T00:20:02.000Z';v.controllerAttemptId=attempt;v.memoryHigh.containerID=cid;v.memoryHigh.observedAt='2026-10-06T00:00:11.000Z';v.manifest.metadata.annotations['evidscope.io/controller-attempt']=attempt;v.manifestSha256=sha(JSON.stringify(v.manifest));v.error=`Command failed: kubectl --kubeconfig .test-runs/evidscope-training/kubeconfig.yaml --request-timeout=10s -n ${QA_NAMESPACE} exec ${v.podName} -- python -c ${command}\nerror: Internal error occurred: Internal error occurred: error executing command in container: failed to exec in container: failed to create exec "${'c'.repeat(64)}": task ${cid} not found\n`;});
 const controller=JSON.parse(readFileSync(resolve(f.root,'controller/controller-receipt.json'))),labels={'io.kubernetes.container.name':'training','io.kubernetes.pod.name':controller.podName,'io.kubernetes.pod.namespace':QA_NAMESPACE,'io.kubernetes.pod.uid':controller.podUid},annotations={'io.kubernetes.container.restartCount':'0'};
 f.edit('controller/live-job.json',v=>v.metadata.annotations={'evidscope.io/controller-attempt':attempt});
 f.edit('controller/live-pod.json',v=>v.status={containerStatuses:[{name:'training',containerID:'containerd://'+cid,imageID:QA_IMAGE,restartCount:0,lastState:{},state:{running:{startedAt:'2026-10-06T00:00:10Z'}}}]});
 const inspection={status:{state:'CONTAINER_EXITED',exitCode:0,reason:'Completed',message:'',id:cid,metadata:{name:'training',attempt:0},annotations,labels,imageRef:QA_IMAGE,createdAt:'2026-10-06T00:00:10.000000000Z',startedAt:'2026-10-06T00:00:10.200000000Z',finishedAt:'2026-10-06T00:20:00.000000000Z'},info:{pid:0,removing:false,config:{metadata:{name:'training'},annotations,labels,image:{user_specified_image:QA_IMAGE}},runtimeSpec:{annotations:{'io.kubernetes.cri.container-name':'training','io.kubernetes.cri.container-type':'container','io.kubernetes.cri.sandbox-name':controller.podName,'io.kubernetes.cri.sandbox-namespace':QA_NAMESPACE,'io.kubernetes.cri.sandbox-uid':controller.podUid,'io.kubernetes.cri.image-name':QA_IMAGE},linux:{cgroupsPath:`/kubepods/burstable/pod${controller.podUid}/${cid}`}}}};
 f.put('controller/cri-inspect.json',inspection);f.options.criInspectionPath=resolve(f.root,'controller/cri-inspect.json');
 return {...f,controller,inspection,reconcile:()=>{const raw=readFileSync(f.options.controllerReceipt);return verifyRuntimeExitReconciliation({controller:JSON.parse(raw),controllerSha256:sha(raw),criInspectionPath:f.options.criInspectionPath,controllerRoot:dirname(f.options.controllerReceipt)});}};
}

test('exact CRI exit reconciles only its cgroup observation race while preserving original controller bytes and synthetic boundaries',async t=>{
 const f=runtimeExitFixture(t),before=readFileSync(f.options.controllerReceipt),proof=await f.verify();
 assert.equal(proof.verificationPassed,true);assert.equal(proof.originalControllerState,'error');assert.equal(proof.originalControllerError,f.controller.error);assert.equal(proof.runtimeExitReconciliation.criInspectionSha256,sha(readFileSync(f.options.criInspectionPath)));assert.equal(proof.runtimeExitReconciliation.originalControllerSha256,sha(before));assert.equal(proof.runtimeExitReconciliation.exitCode,0);assert.equal(proof.runtimeExitReconciliation.imageRef,QA_IMAGE);assert.equal(proof.actualTrainingExecutionVerified,false);assert.equal(proof.trainingRunCompleted,false);assert.deepEqual(readFileSync(f.options.controllerReceipt),before);
 await assert.rejects(verifyPublicQaGroundingContinuation({...f.options,syntheticFixture:true}),/source_pin_changed/);
 await assert.rejects(verifyPublicQaGroundingContinuationFixture({...f.options,criInspectionPath:undefined},f.pins),/controller_execution_unverified/);
});

for(const [name,path,edit,reason]of [
 ['failed exit','controller/cri-inspect.json',v=>v.status.exitCode=1,/cri_exit_not_completed/],
 ['string exit','controller/cri-inspect.json',v=>v.status.exitCode='0',/cri_exit_not_completed/],
 ['missing exit','controller/cri-inspect.json',v=>delete v.status.exitCode,/cri_exit_not_completed/],
 ['nonterminal state','controller/cri-inspect.json',v=>v.status.state='CONTAINER_RUNNING',/cri_exit_not_completed/],
 ['unknown completed reason','controller/cri-inspect.json',v=>v.status.reason='Error',/cri_exit_not_completed/],
 ['invalid header','controller/cri-inspect.json',v=>v.status=[],/cri_receipt_header_invalid/],
 ['other container','controller/cri-inspect.json',v=>v.status.id='d'.repeat(64),/cri_container_identity_changed/],
 ['other Pod UID','controller/cri-inspect.json',v=>v.status.labels['io.kubernetes.pod.uid']='foreign',/cri_pod_identity_changed/],
 ['other namespace','controller/cri-inspect.json',v=>v.info.config.labels['io.kubernetes.pod.namespace']='foreign',/cri_pod_identity_changed/],
 ['restarted container','controller/cri-inspect.json',v=>v.status.metadata.attempt=1,/cri_container_identity_changed/],
 ['restart annotation','controller/cri-inspect.json',v=>v.status.annotations['io.kubernetes.container.restartCount']='1',/cri_container_identity_changed/],
 ['different image digest','controller/cri-inspect.json',v=>v.status.imageRef='foreign',/cri_image_reference_changed/],
 ['missing image digest','controller/cri-inspect.json',v=>delete v.status.imageRef,/cri_image_reference_changed/],
 ['config image mismatch','controller/cri-inspect.json',v=>v.info.config.image.user_specified_image='foreign',/cri_image_reference_changed/],
 ['foreign cgroup','controller/cri-inspect.json',v=>v.info.runtimeSpec.linux.cgroupsPath='/foreign',/cri_runtime_identity_changed/],
 ['finish after controller','controller/cri-inspect.json',v=>v.status.finishedAt='2026-10-06T00:21:00Z',/cri_finish_timing_invalid/],
 ['stale finish','controller/cri-inspect.json',v=>v.status.finishedAt='2026-10-06T00:19:00Z',/cri_finish_timing_invalid/],
 ['invalid calendar','controller/cri-inspect.json',v=>v.status.finishedAt='2026-02-30T00:20:00Z',/cri_finish_timing_invalid/],
 ['other error','controller/controller-receipt.json',v=>v.error='network failure',/cri_controller_error_not_exit_race/],
 ['other task in error','controller/controller-receipt.json',v=>v.error=v.error.replace('task '+'a'.repeat(64),'task '+'d'.repeat(64)),/cri_controller_error_not_exit_race/],
 ['changed probe in error','controller/controller-receipt.json',v=>v.error=v.error.replace('memory.current','memory.peak'),/cri_controller_error_not_exit_race/],
 ['resource guard state','controller/controller-receipt.json',v=>v.state='stopped_by_resource_guard',/cri_controller_state_unreconcilable/],
 ['resource guard reasons','controller/controller-receipt.json',v=>v.stopReasons=['windows_memory_pressure'],/cri_controller_state_unreconcilable/],
 ['cleanup failure','controller/controller-receipt.json',v=>v.cleanupError='not stopped',/cri_controller_state_unreconcilable/],
 ['unconfirmed termination','controller/controller-receipt.json',v=>v.terminationConfirmed=false,/cri_controller_state_unreconcilable/],
 ['foreign observed live CID','controller/live-pod.json',v=>v.status.containerStatuses[0].containerID='containerd://'+'d'.repeat(64),/cri_live_container_binding_changed/],
 ['foreign controller attempt','controller/live-job.json',v=>v.metadata.annotations['evidscope.io/controller-attempt']='foreign',/cri_controller_attempt_changed/],
])test('runtime reconciliation rejects '+name,t=>{const f=runtimeExitFixture(t);f.edit(path,edit);assert.throws(f.reconcile,reason);});

