import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,readdirSync,statSync,rmSync,unlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,dirname,join} from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {verifyPublicQaGroundingDiagnostic,verifyPublicQaGroundingDiagnosticFixture} from '../scripts/verify-public-qa-grounding-diagnostic.mjs';
import {GROUNDING_DIAGNOSTIC_REFERENCE_RUN} from '../scripts/public-qa-grounding-diagnostic-workload.mjs';
import {QA_BASE_REVISION,QA_IMAGE,QA_NAMESPACE,QA_NODE,podSpec} from '../scripts/public-qa-workload.mjs';

const sha=value=>createHash('sha256').update(value).digest('hex'),scope='retrospective_regression_diagnosis_on_previously_observed_64_rows';
function fixture(t){
 const root=mkdtempSync(join(tmpdir(),'evidscope-grounding-diagnostic-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const runId='public-qa-gdiag-fixture',sourceRunId='public-qa-grounding-fixture',runDirectory=resolve(root,'output'),controllerReceipt=resolve(root,'controller/controller-receipt.json');
 const put=(name,value,bom=false)=>{const path=resolve(root,name);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,(bom?'\uFEFF':'')+(typeof value==='string'?value:JSON.stringify(value)));return readFileSync(path);};
 const get=name=>JSON.parse(readFileSync(resolve(root,name),'utf8').replace(/^\uFEFF/,'')),edit=(name,change)=>{const value=get(name);change(value);put(name,value);};
 const pins={data:{},reference:{}},data=Array.from({length:64},(_,index)=>({id:'row-'+index,context:'문서 '+index,contextSha256:sha('문서 '+index)}));
 pins.data.datasetSha256=sha(put('source/data.jsonl',data.map(JSON.stringify).join('\n')+'\n'));pins.data.manifestSha256=sha(put('source/manifest.json',{mode:'public_qa_diagnostic',diagnosticOnly:true,datasetSha256:pins.data.datasetSha256,rowIds:data.map(row=>row.id)}));pins.data.artifactLockSha256=sha(put('source/lock.json',{revision:QA_BASE_REVISION}));
 const identity={baseRevision:QA_BASE_REVISION,baseArtifactLockSha256:pins.data.artifactLockSha256,stage:'public_qa_grounding_v1',precision:'bf16',modelDtype:'bfloat16',quantComputeDtype:'bfloat16',maxSteps:20};
 put('training/candidate/adapter_model.safetensors','synthetic grounding adapter');put('training/candidate/adapter_config.json',{r:8});put('training/candidate/training-receipt.json',{identity,globalStep:20});
 const candidateFiles=readdirSync(resolve(root,'training/candidate')).sort().map(path=>({path,bytes:statSync(resolve(root,'training/candidate',path)).size,sha256:sha(readFileSync(resolve(root,'training/candidate',path)))}));
 const candidateMarkerSha256=sha(put('training/candidate/candidate-complete.json',{schemaVersion:1,globalStep:20,identity,files:candidateFiles})),adapterSha256=candidateFiles.find(file=>file.path==='adapter_model.safetensors').sha256;
 const sourceControllerSha256=sha(put('source/training-controller.json',{runId:sourceRunId,mode:'explicit_public_human_qa_grounding_v1',state:'process_completed',exit:{exitCode:0},terminationConfirmed:true})),sourceRuntimeConfigMapSha256=sha(put('source/training-runtime.json',{data:{fixture:'preserved runtime'}})),provenanceSha256=sha(put('source/provenance.json',{targetRunId:sourceRunId,targetIdentity:identity,optimizerReset:true,schedulerReset:true}));
 const sourceVerificationSha256=sha(put('source/training-verification.json',{verified:true,actualTrainingExecutionVerified:true,sourceTrainingExecutionVerified:true,trainingRunCompleted:true,terminationConfirmed:true,runId:sourceRunId,globalStep:20,actualOptimizerUpdates:20,sourceOptimizerUpdates:40,totalAdapterHistoryOptimizerUpdates:60,skippedOptimizerUpdates:0,optimizerStateRestored:false,schedulerStateRestored:false,qualityClaimAllowed:false,promotionAllowed:false,artifactSha256:candidateMarkerSha256,adapterSha256,adapterTensorVerification:{verified:true,device:'cpu',format:'safetensors',dtype:'F32',tensorCount:256,allFinite:true,sha256:adapterSha256},controllerSha256:sourceControllerSha256,runtimeConfigMapSha256:sourceRuntimeConfigMapSha256,identity}));
 const prior={mode:'public_qa_diagnostic',datasetSha256:pins.data.datasetSha256,maxOutputTokens:128,requestTimeoutSeconds:120,candidate:Object.fromEntries(data.map(row=>[row.id,{content:'기존 후보 출력',seconds:1,inputTokens:50,outputTokens:5,timedOut:false,tokenLimitReached:false}]))};
 pins.reference.responsesSha256=sha(put('reference/responses.json',prior));pins.reference.controllerSha256=sha(put('reference/controller.json',{runId:GROUNDING_DIAGNOSTIC_REFERENCE_RUN,state:'process_completed',exit:{exitCode:0},terminationConfirmed:true}));pins.reference.verificationSha256=sha(put('reference/verification.json',{verificationPassed:true,evaluationExecutionVerified:true,syntheticFixture:false,runId:GROUNDING_DIAGNOSTIC_REFERENCE_RUN,modelCalls:128,admittedRows:64,excludedRows:0,sourceTrainingExecutionVerified:true,controllerReceiptSha256:pins.reference.controllerSha256,responsesSha256:pins.reference.responsesSha256,datasetSha256:pins.data.datasetSha256,qualityClaimAllowed:false,promotionAllowed:false}));
 const binding={schemaVersion:1,mode:'public_qa_grounding_diagnostic',diagnosticOnly:true,sourceRunId,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:60,candidateIdentity:identity,candidateMarkerSha256,adapterSha256,sourceControllerSha256,sourceVerificationSha256,provenanceSha256,artifactLockSha256:pins.data.artifactLockSha256,datasetSha256:pins.data.datasetSha256,manifestSha256:pins.data.manifestSha256,rows:64,priorResponsesSha256:pins.reference.responsesSha256,priorVerificationSha256:pins.reference.verificationSha256,baselineExecutedThisRun:false,evaluationScope:scope,qualityClaimAllowed:false,promotionAllowed:false},bindingSha256=sha(put('source/binding.json',binding));
 const names=['evaluate-public-qa-grounding.py','evaluate-public-qa-diagnostic.py','public_qa_grounding.py','training_artifacts.py','public_qa_cuda_runtime.py','public_qa_memory_gate.py','public_qa_thermal.py'],runtimeData=Object.fromEntries(names.map(name=>[name,'# synthetic '+name+'\n'])),runtimeSha256=sha(JSON.stringify(runtimeData)),runtimeConfigMap='public-qa-gdiag-'+runtimeSha256.slice(0,16),runtimeFiles=Object.fromEntries(Object.entries(runtimeData).map(([name,value])=>[name,sha(value)]));
 put('controller/runtime-configmap.json',{apiVersion:'v1',kind:'ConfigMap',immutable:true,metadata:{name:runtimeConfigMap,namespace:QA_NAMESPACE,annotations:{'evidscope.io/code-sha256':runtimeSha256}},data:runtimeData},true);
 const inputs={...binding,sourceTrainingExecutionVerified:true,sourceRuntimeConfigMapSha256,sourceController:'source/training-controller.json',sourceVerification:'source/training-verification.json',sourceRuntime:'source/training-runtime.json',candidateMarker:'training/candidate/candidate-complete.json',adapter:'training/candidate/adapter_model.safetensors',provenance:'source/provenance.json',data:'source/data.jsonl',manifest:'source/manifest.json',lock:'source/lock.json',bindingPath:'source/binding.json',bindingSha256,binding,priorResponses:'reference/responses.json',priorVerification:'reference/verification.json',priorController:'reference/controller.json',priorControllerSha256:pins.reference.controllerSha256,runtimeConfigMap,runtimeSha256,runtimeFiles};
 const spec=podSpec({gpu:true}),container=spec.containers[0];spec.volumes=spec.volumes.filter(volume=>volume.name!=='checkpoints');container.volumeMounts=container.volumeMounts.filter(mount=>mount.name!=='checkpoints');Object.assign(container.volumeMounts.find(mount=>mount.name==='data'),{mountPath:'/data/diagnostic',subPath:'diagnostic'});
 spec.volumes.push({name:'adapters',persistentVolumeClaim:{claimName:'public-qa-checkpoints',readOnly:true}},{name:'diagnostic-output',persistentVolumeClaim:{claimName:'public-qa-checkpoints'}},{name:'binding',persistentVolumeClaim:{claimName:'public-qa-data',readOnly:true}},{name:'runtime',configMap:{name:runtimeConfigMap}});container.volumeMounts.push({name:'adapters',mountPath:'/adapters/candidate',subPath:`grounding-runs/${sourceRunId}/candidate`,readOnly:true},{name:'diagnostic-output',mountPath:'/checkpoints/diagnostics',subPath:'diagnostics',readOnly:false},{name:'binding',mountPath:'/bindings',subPath:`grounding-diagnostic/${sourceRunId}`,readOnly:true},{name:'runtime',mountPath:'/runtime',readOnly:true});
 container.command=['python','/runtime/evaluate-public-qa-grounding.py'];container.args=['--data','/data/diagnostic/data.jsonl','--manifest','/data/diagnostic/manifest.json','--binding','/bindings/binding.json','--verification','/bindings/verification.json','--provenance','/bindings/provenance.json','--model-dir','/models/foundation-base','--adapter-dir','/adapters/candidate','--output',`/checkpoints/diagnostics/${runId}`];container.env=Object.entries({PYTHONPATH:'/runtime',EVIDSCOPE_MEMORY_HIGH_REQUIRED:'1',EVIDSCOPE_ISOLATED:'1',EVIDSCOPE_GROUNDING_DIAGNOSTIC_BINDING_SHA256:bindingSha256,EVIDSCOPE_DIAGNOSTIC_DATA_SHA256:inputs.datasetSha256,EVIDSCOPE_DIAGNOSTIC_MANIFEST_SHA256:inputs.manifestSha256,EVIDSCOPE_DIAGNOSTIC_CONTROLLER_SHA256:sourceControllerSha256,EVIDSCOPE_DIAGNOSTIC_VERIFICATION_SHA256:sourceVerificationSha256,EVIDSCOPE_DIAGNOSTIC_CANDIDATE_SHA256:candidateMarkerSha256,EVIDSCOPE_DIAGNOSTIC_ADAPTER_SHA256:adapterSha256,EVIDSCOPE_BASE_REPOSITORY:'fdtn-ai/Foundation-Sec-8B-Reasoning',EVIDSCOPE_BASE_REVISION:QA_BASE_REVISION,EVIDSCOPE_BASE_ARTIFACT_LOCK_SHA256:inputs.artifactLockSha256,EVIDSCOPE_TRAINING_IMAGE:QA_IMAGE}).map(([name,value])=>({name,value}));
 const job={metadata:{name:runId,namespace:QA_NAMESPACE,annotations:{'evidscope.io/run-kind':'explicit-public-qa-grounding-diagnostic','evidscope.io/binding-sha256':bindingSha256}},spec:{template:{spec}}},liveSpec={...structuredClone(spec),nodeName:QA_NODE},jobUid='synthetic-job-uid',podUid='synthetic-pod-uid',podName=runId+'-pod';
 const controller={schemaVersion:1,runId,jobUid,podUid,podName,mode:'explicit_public_qa_grounding_diagnostic',diagnosticOnly:true,state:'process_completed',exit:{exitCode:0},terminationConfirmed:true,admission:{allowed:true},trainingRunCompleted:false,qualityClaimAllowed:false,promotionAllowed:false,automaticGovernanceGateClaimed:false,inputs,manifest:job,manifestSha256:sha(JSON.stringify(job)),livePodSpec:liveSpec,memoryHigh:{podUid,markerReleased:true,containerLeafOnly:true,memoryHigh:'2147483648',memoryMax:'12884901888'}};
 put('controller/controller-receipt.json',controller,true);put('controller/live-job.json',{metadata:{uid:jobUid,name:runId,namespace:QA_NAMESPACE},spec:{template:{spec}}});put('controller/live-pod.json',{metadata:{uid:podUid,name:podName,namespace:QA_NAMESPACE,ownerReferences:[{kind:'Job',uid:jobUid,name:runId}]},spec:liveSpec});
 const responses={schemaVersion:1,mode:'public_qa_diagnostic',datasetSha256:inputs.datasetSha256,maxOutputTokens:128,requestTimeoutSeconds:120,baselineExecutedThisRun:false,evaluationScope:scope,priorResponsesSha256:inputs.priorResponsesSha256,candidate:{}},logs=[];
 for(const row of data){const response={content:'새 후보 출력',seconds:1.25,inputTokens:50,outputTokens:5,timedOut:false,tokenLimitReached:false};responses.candidate[row.id]=response;put('output/rows/candidate-'+row.id+'.json',{id:row.id,side:'candidate',...response});logs.push({side:'candidate',id:row.id,modelCalls:logs.length+1,seconds:response.seconds,outputTokens:response.outputTokens,timedOut:false,tokenLimitReached:false});}
 const admission={datasetSha256:inputs.datasetSha256,manifestSha256:inputs.manifestSha256,beforeAnyModelCall:true,answerBasedCropping:false,admitted:64,excluded:0,rows:data.map(row=>({id:row.id,inputTokens:50,outputTokenBudget:128,contextTokens:1024,contextSha256:row.contextSha256,fullContextPreserved:true,admitted:true,exclusionReason:null}))};
 const receipt={schemaVersion:1,mode:'public_qa_grounding_diagnostic',diagnosticOnly:true,source:'isolated_grounding_candidate_generation',state:'generation_completed',podUid,image:QA_IMAGE,deviceId:'synthetic-device',sourceTrainingExecutionVerified:true,controllerExecutionVerified:false,qualityClaimAllowed:false,promotionAllowed:false,localHumanReviewPerformed:false,datasetSha256:inputs.datasetSha256,manifestSha256:inputs.manifestSha256,bindingSha256,candidateMarkerSha256,adapterSha256,baseArtifactLockSha256:inputs.artifactLockSha256,sourceTrainingControllerSha256:sourceControllerSha256,sourceTrainingVerificationSha256:sourceVerificationSha256,sourceRunId,sourceGlobalStep:20,sourceOptimizerHistoryUpdates:60,provenanceSha256,priorResponsesSha256:inputs.priorResponsesSha256,priorVerificationSha256:inputs.priorVerificationSha256,baselineExecutedThisRun:false,evaluationScope:scope,candidateIdentity:identity,modelCalls:64,preparedRows:64,admittedRows:64,excludedRows:0,cudaPeakAllocatedBytes:100,cudaPeakReservedBytes:200,resources:{cpuLimit:2,memoryLimitGiB:12,gpuAllocatorFraction:.65,contextTokens:1024,maxOutputTokens:128,requestTimeoutSeconds:120,seed:42,doSample:false,quantization:'NF4',samePromptsAndResources:true}};
 put('output/responses.json',responses);put('output/preadmission.json',admission);put('output/diagnostic-receipt.json',receipt);put('controller/training.log',logs.map(JSON.stringify).join('\n')+'\n');
 const seal=()=>{const value=get('output/diagnostic-receipt.json');value.responsesSha256=sha(readFileSync(resolve(root,'output/responses.json')));value.preadmissionSha256=sha(readFileSync(resolve(root,'output/preadmission.json')));put('output/diagnostic-receipt.json',value);const {responsesSha256,preadmissionSha256,...progress}=value;put('output/progress.json',progress);};seal();
 const options={runDirectory,controllerReceipt,workspaceRoot:root};return {root,put,get,edit,pins,options,seal,verify:()=>verifyPublicQaGroundingDiagnosticFixture(options,pins)};
}

test('candidate-only64 calls and retrospective reference verify without synthetic execution claims',async t=>{
 const f=fixture(t),result=await f.verify();assert.equal(result.verificationPassed,true);assert.equal(result.evaluationExecutionVerified,false);assert.equal(result.sourceTrainingExecutionVerified,false);assert.equal(result.syntheticFixture,true);assert.equal(result.modelCalls,64);assert.equal(result.baselineExecutedThisRun,false);assert.equal(result.evaluationScope,scope);assert.equal(result.trainingRunCompleted,false);assert.equal(result.qualityClaimAllowed,false);assert.equal(result.promotionAllowed,false);assert.equal(result.sourceRunId,'public-qa-grounding-fixture');await assert.rejects(verifyPublicQaGroundingDiagnostic(f.options),/source_pin_changed/);
});
test('production CLI preserves raw evidence and never accepts fixture pins',async t=>{
 const f=fixture(t),before=readFileSync(f.options.controllerReceipt),output=resolve(f.root,'verification.json'),run=spawnSync(process.execPath,['scripts/verify-public-qa-grounding-diagnostic.mjs',f.options.runDirectory,f.options.controllerReceipt,output],{encoding:'utf8'});assert.equal(run.status,2,run.stderr);const report=JSON.parse(readFileSync(output));assert.equal(report.evaluationExecutionVerified,false);assert.equal(report.trainingRunCompleted,false);assert.equal(report.promotionAllowed,false);assert.match(report.error,/source_pin_changed/);assert.deepEqual(readFileSync(f.options.controllerReceipt),before);
});
test('legitimate ConfigMap API defaults do not invalidate GPU mount evidence',async t=>{const f=fixture(t);f.edit('controller/live-pod.json',pod=>pod.spec.volumes.find(volume=>volume.name==='runtime').configMap.defaultMode=420);assert.equal((await f.verify()).verificationPassed,true);});
for(const [name,path,change,reason]of [
 ['unconfirmed reclamation','controller/controller-receipt.json',value=>value.terminationConfirmed=false,/controller_unverified/],
 ['failed process','controller/controller-receipt.json',value=>value.exit.exitCode=1,/controller_unverified/],
 ['quality promotion','controller/controller-receipt.json',value=>value.promotionAllowed=true,/controller_claim/],
 ['foreign live Pod','controller/live-pod.json',value=>value.metadata.uid='foreign-pod',/job_pod_binding/],
 ['foreign owner Job','controller/live-pod.json',value=>value.metadata.ownerReferences[0].uid='foreign-job',/job_pod_binding/],
 ['foreign GPU node','controller/live-pod.json',value=>value.spec.nodeName='other-node',/node_changed/],
 ['writable candidate','controller/live-pod.json',value=>value.spec.containers[0].volumeMounts.find(mount=>mount.name==='adapters').readOnly=false,/mounts_changed/],
 ['wrong source adapter mount','controller/live-pod.json',value=>value.spec.containers[0].volumeMounts.find(mount=>mount.name==='adapters').subPath='grounding-runs/other/candidate',/mounts_changed/],
 ['wrong binding provenance mount','controller/live-pod.json',value=>value.spec.containers[0].volumeMounts.find(mount=>mount.name==='binding').subPath='grounding-diagnostic/other',/mounts_changed/],
 ['runtime substitution','controller/runtime-configmap.json',value=>value.data['evaluate-public-qa-grounding.py']+='altered',/runtime_changed/],
 ['wrong bound environment','controller/live-pod.json',value=>value.spec.containers[0].env.find(item=>item.name==='EVIDSCOPE_DIAGNOSTIC_ADAPTER_SHA256').value='f'.repeat(64),/environment_changed/],
 ['wrong generation Pod','output/diagnostic-receipt.json',value=>value.podUid='foreign-pod',/generation_unverified/],
 ['pretended new baseline calls','output/diagnostic-receipt.json',value=>value.baselineExecutedThisRun=true,/receipt_binding/],
 ['128 calls claimed for64 new calls','output/diagnostic-receipt.json',value=>value.modelCalls=128,/call_or_admission_count/],
 ['unobserved acceptance claim','output/diagnostic-receipt.json',value=>value.evaluationScope='untouched_heldout_acceptance',/receipt_binding/],
 ['answer cropping','output/preadmission.json',value=>value.rows[0].fullContextPreserved=false,/full_context_admission/],
 ['missing admission row','output/preadmission.json',value=>value.rows.pop(),/call_or_admission_count/],
 ['output token overflow','output/responses.json',value=>value.candidate['row-0'].outputTokens=129,/response_measurement/],
 ['injected baseline response map','output/responses.json',value=>value.baseline={},/candidate_only_responses/],
 ['omitted candidate result','output/responses.json',value=>delete value.candidate['row-0'],/candidate_only_responses/],
])test('grounding diagnostic rejects '+name,async t=>{const f=fixture(t);f.edit(path,change);if(path.startsWith('output/'))f.seal();await assert.rejects(f.verify(),reason);});

test('raw rows and stdout must match actual64 candidate calls despite resealed response hashes',async t=>{
 const f=fixture(t);f.edit('output/responses.json',value=>value.candidate['row-0'].content='altered output');f.seal();await assert.rejects(f.verify(),/partial_changed/);
 const g=fixture(t);g.put('controller/training.log','{}\n');await assert.rejects(g.verify(),/generation_log/);
 const h=fixture(t);unlinkSync(resolve(h.root,'output/rows/candidate-row-0.json'));await assert.rejects(h.verify(),/ENOENT/);
});
test('retrospective proof cannot conceal missing prior execution or a changed source optimizer history',async t=>{
 const f=fixture(t);f.edit('reference/verification.json',value=>value.evaluationExecutionVerified=false);f.pins.reference.verificationSha256=sha(readFileSync(resolve(f.root,'reference/verification.json')));f.edit('controller/controller-receipt.json',value=>value.inputs.priorVerificationSha256=f.pins.reference.verificationSha256);f.edit('source/binding.json',value=>value.priorVerificationSha256=f.pins.reference.verificationSha256);const binding=f.get('source/binding.json'),hash=sha(readFileSync(resolve(f.root,'source/binding.json')));f.edit('controller/controller-receipt.json',value=>{value.inputs.binding=binding;value.inputs.bindingSha256=hash;});await assert.rejects(f.verify(),/retrospective_reference_unverified/);
 const g=fixture(t);g.edit('source/training-verification.json',value=>value.actualOptimizerUpdates=60);const newHash=sha(readFileSync(resolve(g.root,'source/training-verification.json')));g.edit('controller/controller-receipt.json',value=>value.inputs.sourceVerificationSha256=newHash);await assert.rejects(g.verify(),/source_training_unverified/);
});
test('changed source or baseline bytes cannot be substituted by a different candidate or comparison',async t=>{
 const f=fixture(t);f.put('training/candidate/adapter_model.safetensors','other weights');await assert.rejects(f.verify(),/source_file_changed:adapter/);
 const g=fixture(t);g.edit('reference/responses.json',value=>value.candidate['row-0'].content='other baseline');await assert.rejects(g.verify(),/source_file_changed:priorResponses/);
});
