import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {REVISION,PINS,sha,selectDiagnosticRows,prepareDiagnostic,verifySourceArtifacts} from '../scripts/public-qa-diagnostic-data.mjs';
import {scoreResponse,scoreDiagnostic,normalizeAnswer} from '../scripts/score-public-qa-diagnostic.mjs';

// Test-only invented QA/output fixtures. These are never exported as model responses or reviewed data.
function row(id='a',impossible=false){const context='문서에는 서울과 부산이 나온다.',answers=impossible?[]:[{text:'서울',answer_start:5}];return {id,familyId:'family-'+id,split:'heldout',upstreamSplit:'dev',upstreamRevision:REVISION,language:'ko',sourceLicense:'CC-BY-SA-4.0',context,contextSha256:sha(context),question:'문서의 첫 도시는?',answers,isImpossible:impossible,upstreamAnnotation:{kind:'human_authored_question_answer_spans',localHumanReviewPerformed:false},originalQa:{question:'문서의 첫 도시는?',answers:structuredClone(answers),is_impossible:impossible}};}
function response(value={answer:'서울',evidenceQuote:'문서에는 서울과 부산이 나온다.',abstained:false},extra={}){return {content:JSON.stringify(value),seconds:2,inputTokens:20,outputTokens:15,timedOut:false,tokenLimitReached:false,...extra};}
const limits={maxOutputTokens:128,requestTimeoutSeconds:120};
function cleanTemporary(dir){assert.equal(dirname(resolve(dir)),resolve(tmpdir()));assert.ok(resolve(dir).startsWith(join(resolve(tmpdir()),'qa-diag-')));rmSync(dir,{recursive:true,force:true});}
function batch(){const rows=[row('a'),row('b',true)],dataBytes=Buffer.from(rows.map(r=>JSON.stringify(r)).join('\n')+'\n'),manifest={schemaVersion:1,mode:'public_qa_diagnostic',diagnosticOnly:true,localHumanReviewPerformed:false,qualityClaimAllowed:false,promotionAllowed:false,sourcePins:PINS,datasetSha256:sha(dataBytes),counts:{total:2},rowIds:['a','b']},outputs={a:response(),b:response({answer:'',evidenceQuote:'',abstained:true})};return {dataBytes,manifest,responses:{schemaVersion:1,mode:'public_qa_diagnostic',datasetSha256:manifest.datasetSha256,...limits,baseline:structuredClone(outputs),candidate:structuredClone(outputs)}};}

test('selection is deterministic and preserves full original context and annotation truth',()=>{const a=row('a'),b=row('b',true),c=row('c'),d=row('d',true);const first=selectDiagnosticRows([d,c,b,a],[],{perClass:1,maxContextCharacters:100});const second=selectDiagnosticRows([a,b,c,d],[],{perClass:1,maxContextCharacters:100});assert.deepEqual(first,second);assert.deepEqual(first.rows.map(r=>r.id),['a','b']);assert.equal(first.rows[0].context,a.context);assert.equal(first.rows[0].localHumanReviewPerformed,false);assert.equal(first.rows[0].privacyScreen.comprehensivePrivacyReview,false);});
for(const field of ['id','familyId','contextSha256'])test(`reject heldout overlap by ${field} before subset filtering`,()=>{const a=row('a'),b=row('b',true);assert.throws(()=>selectDiagnosticRows([a,b],[{[field]:a[field]}],{perClass:1}),/training_heldout_overlap/);});
test('reject original answer forgery even if context hash is updated',()=>{const a=row();a.answers=[{text:'제주',answer_start:5}];assert.throws(()=>selectDiagnosticRows([a,row('b',true)],[],{perClass:1}),/original_annotation_changed/);});
test('reject forged original answer span and context modification',()=>{const a=row();a.context+='변조';assert.throws(()=>selectDiagnosticRows([a],[],{perClass:1}),/heldout_content_invalid/);const b=row();b.answers[0].answer_start=0;b.originalQa.answers=structuredClone(b.answers);assert.throws(()=>selectDiagnosticRows([b],[],{perClass:1}),/answer_span_invalid/);});
test('a long full context is excluded rather than answer-centered cropping',()=>{const a=row();assert.throws(()=>selectDiagnosticRows([a,row('b',true)],[],{perClass:1,maxContextCharacters:3}),/insufficient_diagnostic_rows/);assert.equal(a.context,'문서에는 서울과 부산이 나온다.');});
test('duplicate IDs and fake local review are rejected',()=>{assert.throws(()=>selectDiagnosticRows([row(),row()],[],{perClass:1}),/duplicate_heldout_id/);const a=row();a.localHumanReviewPerformed=true;assert.throws(()=>selectDiagnosticRows([a],[],{perClass:1}),/annotation_provenance_invalid/);});
test('privacy patterns exclude the entire row without claiming comprehensive review',()=>{const a=row();a.question+=' user@example.com';a.originalQa.question=a.question;assert.throws(()=>selectDiagnosticRows([a,row('b',true)],[],{perClass:1}),/insufficient_diagnostic_rows/);});
test('pinned preparation refuses changed manifest before creating any output',()=>{const dir=mkdtempSync(join(tmpdir(),'qa-diag-'));try{mkdirSync(join(dir,'source'));mkdirSync(join(dir,'train'));writeFileSync(join(dir,'source/manifest.json'),'{}');writeFileSync(join(dir,'train/public-qa-stage1.manifest.json'),'{}');assert.throws(()=>prepareDiagnostic({source:join(dir,'source'),training:join(dir,'train'),output:join(dir,'out')}),/pinned_manifest_mismatch/);}finally{cleanTemporary(dir);}});
test('source artifact verification rejects altered bytes and path escapes',()=>{const dir=mkdtempSync(join(tmpdir(),'qa-diag-'));try{writeFileSync(join(dir,'raw.json'),'tampered');assert.throws(()=>verifySourceArtifacts(dir,{raw:[{path:'raw.json',sha256:sha('original')}],outputs:[]}),/source_artifact_changed/);assert.throws(()=>verifySourceArtifacts(dir,{raw:[{path:'../outside.json',sha256:sha('original')}],outputs:[]}),/source_path_escape/);}finally{cleanTemporary(dir);}});
test('exact answer with full context quote passes; an answer without supporting quote fails',()=>{assert.equal(scoreResponse(row(),response(),limits).passed,true);const v=scoreResponse(row(),response({answer:'서울',evidenceQuote:'',abstained:false}),limits);assert.equal(v.exactAnswer,true);assert.equal(v.quoteGrounded,false);assert.equal(v.passed,false);});
test('forged quote and quote about another answer cannot pass grounding',()=>{for(const evidenceQuote of ['서울은 문서에서 승인되었다.','부산']){const v=scoreResponse(row(),response({answer:'서울',evidenceQuote,abstained:false}),limits);assert.equal(v.exactAnswer,true);assert.equal(v.quoteGrounded,false);assert.equal(v.passed,false);}});
test('correct abstention requires both fields empty and flag true',()=>{const impossible=row('b',true);assert.equal(scoreResponse(impossible,response({answer:'',evidenceQuote:'',abstained:true}),limits).passed,true);assert.equal(scoreResponse(impossible,response({answer:'없음',evidenceQuote:'',abstained:true}),limits).passed,false);assert.equal(scoreResponse(row(),response({answer:'',evidenceQuote:'',abstained:true}),limits).passed,false);});
test('JSON failure and unsupported legal approval field count as failures',()=>{for(const content of ['not JSON','```json\n{}\n```','{"answer":"서울","evidenceQuote":"서울","abstained":false,"approved":true}']){const scored=scoreResponse(row(),response(undefined,{content}),limits);assert.equal(scored.passed,false);assert.equal(scored.formatValid,false);}});
test('timeout, token exhaustion and inference error fail even with correct content',()=>{for(const extra of [{timedOut:true},{seconds:120},{tokenLimitReached:true},{outputTokens:128},{error:'OOM'},{inputTokens:0}])assert.equal(scoreResponse(row(),response(undefined,extra),limits).passed,false);});
test('normalization is NFC and whitespace only, not semantic equivalence',()=>{assert.equal(normalizeAnswer('  서울\n 부산 '),'서울 부산');const scored=scoreResponse(row(),response({answer:' 서울 ',evidenceQuote:'서울',abstained:false}),limits);assert.equal(scored.normalizedAnswer,true);assert.equal(scored.exactAnswer,false);assert.equal(scored.passed,false);assert.notEqual(normalizeAnswer('서울.'),normalizeAnswer('서울'));});
test('all original human answer alternatives are accepted',()=>{const a=row();a.answers.push({text:'부산',answer_start:9});a.originalQa.answers=structuredClone(a.answers);assert.equal(scoreResponse(a,response({answer:'부산',evidenceQuote:'부산',abstained:false}),limits).passed,true);});
test('missing outputs count as failures with unchanged denominator; no model execution claim',()=>{const b=batch();delete b.responses.candidate.b;const result=scoreDiagnostic(b);assert.equal(result.candidate.count,2);assert.equal(result.candidate.passed.rate,.5);assert.equal(result.candidate.failures[0].reason,'missing_output');assert.equal(result.actualModelExecutionVerified,false);assert.equal(result.promotionAllowed,false);assert.equal(result.qualityClaimAllowed,false);});
test('scorer rejects swapped data hash or extra response IDs',()=>{const b=batch();b.responses.datasetSha256='0'.repeat(64);assert.throws(()=>scoreDiagnostic(b),/diagnostic_measurement_binding_invalid/);const c=batch();c.responses.candidate.stranger=response();assert.throws(()=>scoreDiagnostic(c),/unexpected_response_ids/);const d=batch();d.dataBytes=Buffer.from(d.dataBytes+' ');assert.throws(()=>scoreDiagnostic(d),/diagnostic_dataset_binding_invalid/);});
