import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {EventEmitter} from 'node:events';
import {createTestRuntime,TEST_RUNTIME_SCOPE,runOwnedTestProcess} from '../scripts/test-runtime-lib.mjs';

function fixture({ollama=false,k3d=false,failK3dStart=false,clock=()=>1000,pidAlive=()=>true}={}){mkdirSync('.test-runs',{recursive:true});const root=mkdtempSync(resolve('.test-runs/test-runtime-')),kubeconfig=join(root,...TEST_RUNTIME_SCOPE.kubeconfig.split('/'));mkdirSync(resolve(kubeconfig,'..'),{recursive:true});writeFileSync(kubeconfig,'synthetic kubeconfig; never parsed by test\n');const calls=[];let dockerRunning=ollama,clusterRunning=k3d;
 const run=(program,args)=>{calls.push([program,...args]);if(program==='docker'&&args[0]==='inspect')return {status:0,stdout:`/${TEST_RUNTIME_SCOPE.container}\t${dockerRunning}\t${dockerRunning?'running':'exited'}\n`,stderr:''};if(program==='docker'&&args[0]==='start'){dockerRunning=true;return {status:0,stdout:TEST_RUNTIME_SCOPE.container,stderr:''};}if(program==='docker'&&args[0]==='stop'){dockerRunning=false;return {status:0,stdout:TEST_RUNTIME_SCOPE.container,stderr:''};}if(program==='k3d'&&args[1]==='list')return {status:0,stdout:JSON.stringify([{name:TEST_RUNTIME_SCOPE.cluster,serversRunning:clusterRunning?1:0,agentsRunning:clusterRunning?2:0}]),stderr:''};if(program==='k3d'&&args[1]==='start'){if(failK3dStart)return {status:1,stdout:'',stderr:'not exposed'};clusterRunning=true;return {status:0,stdout:'',stderr:''};}if(program==='k3d'&&args[1]==='stop'){clusterRunning=false;return {status:0,stdout:'',stderr:''};}if(program==='kubectl')return {status:0,stdout:TEST_RUNTIME_SCOPE.context+'\n',stderr:''};throw Error(`unexpected command ${program}`);};return {runtime:createTestRuntime({root,run,clock,pidAlive}),calls,state:()=>({dockerRunning,clusterRunning}),root};}

test('test runtime refuses pre-existing resources and never adopts another owner',()=>{const f=fixture({ollama:true});assert.throws(()=>f.runtime.start({resources:['ollama']}),e=>e.code==='TEST_RUNTIME_PREEXISTING');assert.equal(f.calls.some(call=>call[1]==='start'),false);assert.equal(existsSync(f.runtime.leasePath),false);});

test('explicit lease starts and stops only exact EvidScope names without delete commands',()=>{const f=fixture(),lease=f.runtime.start({mode:'manual',ownerLabel:'unit-test',resources:['ollama','k3d']});assert.deepEqual(lease.startedResources,['ollama','k3d']);assert.deepEqual(f.state(),{dockerRunning:true,clusterRunning:true});const stopped=f.runtime.stop(lease.leaseId);assert.deepEqual(stopped.stopped,['k3d','ollama']);assert.deepEqual(f.state(),{dockerRunning:false,clusterRunning:false});assert.ok(f.calls.some(call=>call.join(' ')==='docker start evidscope-ollama-assistance-20260909'));assert.ok(f.calls.some(call=>call.join(' ')==='k3d cluster start evidscope-lab-20260908'));assert.ok(f.calls.every(call=>!call.includes('rm')&&!call.includes('delete')));assert.equal(stopped.volumesPreserved,true);});

test('partial start failure cleans its own attempted resource and removes lease',()=>{const f=fixture({failK3dStart:true});assert.throws(()=>f.runtime.start({resources:['ollama','k3d']}),e=>e.code==='TEST_RUNTIME_COMMAND');assert.deepEqual(f.state(),{dockerRunning:false,clusterRunning:false});assert.equal(existsSync(f.runtime.leasePath),false);assert.ok(f.calls.some(call=>call[0]==='docker'&&call[1]==='stop'));});

test('manual idle and dead wrapper require explicit reconcile before cleanup',()=>{let now=1000;const manual=fixture({clock:()=>now}),first=manual.runtime.start({mode:'manual',idleMs:60000,resources:['ollama']});assert.throws(()=>manual.runtime.reconcile(first.leaseId),e=>e.code==='TEST_RUNTIME_LIVE_OWNER');now+=60001;assert.equal(manual.runtime.status().lease.reconciliationRequired,true);manual.runtime.reconcile(first.leaseId);assert.deepEqual(manual.state(),{dockerRunning:false,clusterRunning:false});const wrapper=fixture({pidAlive:()=>false}),second=wrapper.runtime.start({mode:'wrapper',ownerPid:99999,resources:['k3d']});assert.equal(wrapper.runtime.status().lease.reconciliationRequired,true);assert.equal(wrapper.runtime.reconcile(second.leaseId).reason,'dead_wrapper_owner');});

test('owned wrapper cleans resources after normal exit, child error, and interrupt',async()=>{for(const outcome of ['normal','error','interrupt']){const f=fixture(),signals=new EventEmitter(),child=new EventEmitter();child.killed=false;child.exitCode=null;child.kill=signal=>{child.killed=true;queueMicrotask(()=>child.emit('exit',null,signal));return true;};const promise=runOwnedTestProcess(f.runtime,{program:'synthetic-test',resources:['ollama'],signalEmitter:signals,spawnChild:()=>{if(outcome==='normal')queueMicrotask(()=>{child.exitCode=0;child.emit('exit',0,null);});if(outcome==='error')queueMicrotask(()=>child.emit('error',Error('synthetic failure')));if(outcome==='interrupt')queueMicrotask(()=>signals.emit('SIGINT'));return child;}});if(outcome==='error')await assert.rejects(promise,/synthetic failure/);else{const result=await promise;if(outcome==='interrupt')assert.equal(result.interruptedBy,'SIGINT');}assert.deepEqual(f.state(),{dockerRunning:false,clusterRunning:false});assert.equal(existsSync(f.runtime.leasePath),false);}});
