import {modelPolicy} from '../../src/model-policy.mjs';
import {pathToFileURL} from 'node:url';
const ns='evidscope-models';
const securityContext={runAsNonRoot:true,runAsUser:10001,runAsGroup:10001,allowPrivilegeEscalation:false,readOnlyRootFilesystem:true,capabilities:{drop:['ALL']},seccompProfile:{type:'RuntimeDefault'}};
const offline=[{name:'EVIDSCOPE_ISOLATED',value:'1'},{name:'HF_HUB_OFFLINE',value:'1'},{name:'TRANSFORMERS_OFFLINE',value:'1'},{name:'HF_HUB_DISABLE_TELEMETRY',value:'1'},{name:'PYTHONDONTWRITEBYTECODE',value:'1'}];
export function modelRuntimeManifest(){
 const items=[{apiVersion:'v1',kind:'Namespace',metadata:{name:ns,labels:{'pod-security.kubernetes.io/enforce':'restricted','pod-security.kubernetes.io/audit':'restricted','pod-security.kubernetes.io/warn':'restricted'}}},
 {apiVersion:'v1',kind:'ServiceAccount',metadata:{name:'model-no-api',namespace:ns},automountServiceAccountToken:false},
 {apiVersion:'networking.k8s.io/v1',kind:'NetworkPolicy',metadata:{name:'deny-all',namespace:ns},spec:{podSelector:{},policyTypes:['Ingress','Egress'],ingress:[],egress:[]}},
 {apiVersion:'networking.k8s.io/v1',kind:'NetworkPolicy',metadata:{name:'dispatcher-to-model-mtls',namespace:ns},spec:{podSelector:{matchLabels:{'evidscope.io/component':'isolated-model'}},policyTypes:['Ingress'],ingress:[{from:[{namespaceSelector:{matchLabels:{'kubernetes.io/metadata.name':'evidscope'}},podSelector:{matchLabels:{'evidscope.io/component':'model-dispatcher'}}}],ports:[{protocol:'TCP',port:8443}]}]}}];
 for(const policy of [modelPolicy.primary,modelPolicy.cipher]){
  const primary=policy.id==='foundation-sec',labels={'evidscope.io/component':'isolated-model','evidscope.io/model':policy.id,'evidscope.io/managed':'true'};
  const model={name:'model',image:`evidscope/${primary?'foundation-runtime':'cipher-runtime'}:UNPINNED-BLOCKED`,imagePullPolicy:'Never',securityContext,env:offline,resources:{requests:{cpu:primary?'1900m':'900m',memory:primary?'7936Mi':'3840Mi'},limits:{cpu:primary?'1900m':'900m',memory:primary?'7936Mi':'3840Mi'}},volumeMounts:[{name:'models',mountPath:'/models',readOnly:true},{name:'temporary',mountPath:'/tmp'},{name:'podinfo',mountPath:'/etc/podinfo',readOnly:true}],command:primary?['/app/llama-server']:['python','/app/cipher_service.py'],args:primary?['--model','/models/foundation-sec/foundation-sec-1.1-8b-instruct-q4_k_m.gguf','--alias',policy.model,'--host','127.0.0.1','--port','8080','--ctx-size','2048','--n-predict','512','--parallel','1','--threads','2','--threads-batch','2','--no-webui','--no-slots','--log-disable','--no-context-shift']:[]};
  const frontend={name:'mtls',image:'evidscope/model-tls:UNPINNED-BLOCKED',imagePullPolicy:'Never',command:['python','/app/tls_frontend.py'],securityContext,env:[...offline,{name:'MODEL_KIND',value:policy.id}],ports:[{containerPort:8443,name:'mtls'}],resources:{requests:{cpu:'100m',memory:'256Mi'},limits:{cpu:'100m',memory:'256Mi'}},volumeMounts:[{name:'tls',mountPath:'/tls',readOnly:true}],readinessProbe:{tcpSocket:{port:8443},periodSeconds:2},startupProbe:{tcpSocket:{port:8443},periodSeconds:2,failureThreshold:60}};
  if(primary)model.command=['python','/app/foundation_entry.py'];
  model.readinessProbe={exec:{command:['python','-c',`import urllib.request; urllib.request.urlopen('http://127.0.0.1:${primary?8080:8091}/health', timeout=1)`]},periodSeconds:2,timeoutSeconds:2};
  model.startupProbe={...model.readinessProbe,failureThreshold:primary?85:40};
  items.push({apiVersion:'batch/v1',kind:'Job',metadata:{name:policy.id,namespace:ns,labels,annotations:{'evidscope.io/activation':'blocked: pin images, verify artifacts, mount mTLS, measure CNI isolation, then dispatcher creates per-run job'}},spec:{suspend:true,parallelism:1,completions:1,backoffLimit:0,activeDeadlineSeconds:primary?300:180,ttlSecondsAfterFinished:60,template:{metadata:{labels},spec:{serviceAccountName:'model-no-api',automountServiceAccountToken:false,enableServiceLinks:false,hostNetwork:false,hostPID:false,hostIPC:false,shareProcessNamespace:false,restartPolicy:'Never',terminationGracePeriodSeconds:5,securityContext:{runAsNonRoot:true,runAsUser:10001,runAsGroup:10001,fsGroup:10001,seccompProfile:{type:'RuntimeDefault'}},containers:[model,frontend],volumes:[{name:'models',persistentVolumeClaim:{claimName:`${policy.id}-approved-model`,readOnly:true}},{name:'temporary',emptyDir:{medium:'Memory',sizeLimit:'64Mi'}},{name:'tls',secret:{secretName:`${policy.id}-server-tls`,defaultMode:288}},{name:'podinfo',downwardAPI:{items:[{path:'uid',fieldRef:{fieldPath:'metadata.uid'}}]}}]}}}});
  items.push({apiVersion:'v1',kind:'Service',metadata:{name:policy.id,namespace:ns},spec:{type:'ClusterIP',selector:labels,ports:[{name:'mtls',port:8443,targetPort:8443}]}});
 }
 return {apiVersion:'v1',kind:'List',items};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)process.stdout.write(JSON.stringify(modelRuntimeManifest(),null,2)+'\n');
