// Read-only manifest validation. Does not execute PowerShell, kubectl or deploy resources.
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const manifest=JSON.parse(readFileSync('deploy/kubernetes.json','utf8'));
assert.equal(manifest.kind,'List');const items=manifest.items,deployments=items.filter(x=>x.kind==='Deployment');
assert.deepEqual(new Set(deployments.map(x=>x.metadata.name)),new Set(['vault','ingress','audit','worker']));
for(const d of deployments){const pod=d.spec.template.spec,c=pod.containers[0],env=Object.fromEntries(c.env.filter(e=>'value'in e).map(e=>[e.name,e.value]));
 assert.equal(pod.automountServiceAccountToken,false,d.metadata.name+' service token');assert.equal(pod.securityContext.runAsNonRoot,true);assert.equal(pod.securityContext.seccompProfile.type,'RuntimeDefault');assert.equal(c.securityContext.readOnlyRootFilesystem,true);assert.equal(c.securityContext.allowPrivilegeEscalation,false);assert.ok(c.securityContext.capabilities.drop.includes('ALL'));assert.ok(c.resources.requests.cpu&&c.resources.limits.memory);assert.equal(c.readinessProbe.httpGet.scheme,'HTTPS');assert.equal(c.livenessProbe.httpGet.scheme,'HTTPS');
 assert.ok(env.TLS_CERT_FILE&&env.TLS_KEY_FILE);if(d.metadata.name==='vault'){assert.equal(d.spec.replicas,1);assert.equal(d.spec.strategy.type,'Recreate');assert.ok(pod.volumes.some(v=>v.secret?.secretName==='vault-signing'));}
 else{assert.ok(env.VAULT_URL.startsWith('https://'));assert.ok(env.NODE_EXTRA_CA_CERTS);assert.ok(!pod.volumes.some(v=>v.persistentVolumeClaim||v.secret?.secretName==='vault-signing'||v.secret?.secretName==='vault-config'));assert.equal(d.spec.replicas,2);assert.deepEqual(d.spec.strategy,{type:'RollingUpdate',rollingUpdate:{maxUnavailable:0,maxSurge:1}});assert.ok(pod.topologySpreadConstraints.some(s=>s.topologyKey==='kubernetes.io/hostname'&&s.minDomains===2&&s.whenUnsatisfiable==='DoNotSchedule'));}
 assert.equal(c.readinessProbe.httpGet.path,'/readyz');assert.equal(c.livenessProbe.httpGet.path,'/healthz');assert.equal(c.startupProbe.httpGet.path,'/healthz');assert.ok(c.env.some(e=>e.name==='POD_NAME'&&e.valueFrom?.fieldRef?.fieldPath==='metadata.name'));
}
for(const svc of items.filter(x=>x.kind==='Service')){assert.equal(svc.spec.type,'ClusterIP');assert.equal(svc.spec.sessionAffinity,'None');assert.equal(svc.spec.internalTrafficPolicy,'Cluster');assert.equal(svc.spec.publishNotReadyAddresses,false);const d=deployments.find(d=>d.metadata.name===svc.metadata.name);assert.ok(d);for(const [key,value]of Object.entries(svc.spec.selector))assert.equal(d.spec.template.metadata.labels[key],value);}
assert.ok(items.some(x=>x.kind==='NetworkPolicy'&&x.metadata.name==='deny-all'&&x.spec.policyTypes.includes('Ingress')&&x.spec.policyTypes.includes('Egress')));
assert.equal(items.filter(x=>x.kind==='Secret').length,0);assert.equal(items.filter(x=>x.kind==='HorizontalPodAutoscaler').length,3);
const distribution=JSON.parse(readFileSync('deploy/distribution-jobs.json','utf8'));
for(const job of distribution.items.filter(x=>x.kind==='Job')){const p=job.spec.template.spec,c=p.containers[0];assert.equal(p.automountServiceAccountToken,false);assert.equal(p.restartPolicy,'Never');assert.equal(job.spec.backoffLimit,0);assert.deepEqual(c.command,['node','scripts/k8s-distribution.mjs']);assert.ok(c.env.some(e=>e.name==='EXPECTED_MIN_INSTANCES'&&e.value==='2'));assert.ok(!p.volumes.some(v=>['vault-config','vault-signing'].includes(v.secret?.secretName)));assert.equal(c.securityContext.readOnlyRootFilesystem,true);}
console.log(JSON.stringify({pass:true,resources:items.length,distributionJobs:distribution.items.filter(x=>x.kind==='Job').length,scope:'Read-only JSON security checks; not Kubernetes schema admission, CNI, TLS runtime, HPA or deployment verification'}));
